// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Elmo from "../../../index.js";

export declare namespace CompetitorsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Manage brand competitors
 */
export class CompetitorsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<CompetitorsClient.Options>;

    constructor(options: CompetitorsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {Elmo.ListCompetitorsRequest} request
     * @param {CompetitorsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Elmo.UnauthorizedError}
     * @throws {@link Elmo.ForbiddenError}
     * @throws {@link Elmo.TooManyRequestsError}
     * @throws {@link Elmo.InternalServerError}
     * @throws {@link errors.ElmoError}
     * @throws {@link errors.ElmoTimeoutError}
     *
     * @example
     *     await client.competitors.listCompetitors()
     */
    public listCompetitors(
        request: Elmo.ListCompetitorsRequest = {},
        requestOptions?: CompetitorsClient.RequestOptions,
    ): core.HttpResponsePromise<Elmo.CompetitorsList> {
        return core.HttpResponsePromise.fromPromise(this.__listCompetitors(request, requestOptions));
    }

    private async __listCompetitors(
        request: Elmo.ListCompetitorsRequest = {},
        requestOptions?: CompetitorsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Elmo.CompetitorsList>> {
        const { brandId, page, limit } = request;
        const _queryParams: Record<string, unknown> = {
            brandId,
            page,
            limit,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ElmoEnvironment.Default,
                "competitors",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Elmo.CompetitorsList, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Elmo.UnauthorizedError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 403:
                    throw new Elmo.ForbiddenError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 429:
                    throw new Elmo.TooManyRequestsError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 500:
                    throw new Elmo.InternalServerError(_response.error.body as Elmo.Error_, _response.rawResponse);
                default:
                    throw new errors.ElmoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/competitors");
    }

    /**
     * @param {Elmo.CreateCompetitorRequest} request
     * @param {CompetitorsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Elmo.BadRequestError}
     * @throws {@link Elmo.UnauthorizedError}
     * @throws {@link Elmo.PaymentRequiredError}
     * @throws {@link Elmo.ForbiddenError}
     * @throws {@link Elmo.ConflictError}
     * @throws {@link Elmo.TooManyRequestsError}
     * @throws {@link Elmo.InternalServerError}
     * @throws {@link errors.ElmoError}
     * @throws {@link errors.ElmoTimeoutError}
     *
     * @example
     *     await client.competitors.createCompetitor({
     *         brandId: "brandId",
     *         name: "name"
     *     })
     */
    public createCompetitor(
        request: Elmo.CreateCompetitorRequest,
        requestOptions?: CompetitorsClient.RequestOptions,
    ): core.HttpResponsePromise<Elmo.Competitor> {
        return core.HttpResponsePromise.fromPromise(this.__createCompetitor(request, requestOptions));
    }

    private async __createCompetitor(
        request: Elmo.CreateCompetitorRequest,
        requestOptions?: CompetitorsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Elmo.Competitor>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ElmoEnvironment.Default,
                "competitors",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Elmo.Competitor, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Elmo.BadRequestError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 401:
                    throw new Elmo.UnauthorizedError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 402:
                    throw new Elmo.PaymentRequiredError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 403:
                    throw new Elmo.ForbiddenError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 409:
                    throw new Elmo.ConflictError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 429:
                    throw new Elmo.TooManyRequestsError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 500:
                    throw new Elmo.InternalServerError(_response.error.body as Elmo.Error_, _response.rawResponse);
                default:
                    throw new errors.ElmoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/competitors");
    }

    /**
     * @param {Elmo.GetCompetitorRequest} request
     * @param {CompetitorsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Elmo.BadRequestError}
     * @throws {@link Elmo.UnauthorizedError}
     * @throws {@link Elmo.ForbiddenError}
     * @throws {@link Elmo.NotFoundError}
     * @throws {@link Elmo.TooManyRequestsError}
     * @throws {@link Elmo.InternalServerError}
     * @throws {@link errors.ElmoError}
     * @throws {@link errors.ElmoTimeoutError}
     *
     * @example
     *     await client.competitors.getCompetitor({
     *         competitorId: "competitorId"
     *     })
     */
    public getCompetitor(
        request: Elmo.GetCompetitorRequest,
        requestOptions?: CompetitorsClient.RequestOptions,
    ): core.HttpResponsePromise<Elmo.Competitor> {
        return core.HttpResponsePromise.fromPromise(this.__getCompetitor(request, requestOptions));
    }

    private async __getCompetitor(
        request: Elmo.GetCompetitorRequest,
        requestOptions?: CompetitorsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Elmo.Competitor>> {
        const { competitorId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ElmoEnvironment.Default,
                `competitors/${core.url.encodePathParam(competitorId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Elmo.Competitor, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Elmo.BadRequestError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 401:
                    throw new Elmo.UnauthorizedError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 403:
                    throw new Elmo.ForbiddenError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 404:
                    throw new Elmo.NotFoundError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 429:
                    throw new Elmo.TooManyRequestsError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 500:
                    throw new Elmo.InternalServerError(_response.error.body as Elmo.Error_, _response.rawResponse);
                default:
                    throw new errors.ElmoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/competitors/{competitorId}");
    }

    /**
     * @param {Elmo.DeleteCompetitorRequest} request
     * @param {CompetitorsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Elmo.BadRequestError}
     * @throws {@link Elmo.UnauthorizedError}
     * @throws {@link Elmo.PaymentRequiredError}
     * @throws {@link Elmo.ForbiddenError}
     * @throws {@link Elmo.NotFoundError}
     * @throws {@link Elmo.ConflictError}
     * @throws {@link Elmo.TooManyRequestsError}
     * @throws {@link Elmo.InternalServerError}
     * @throws {@link errors.ElmoError}
     * @throws {@link errors.ElmoTimeoutError}
     *
     * @example
     *     await client.competitors.deleteCompetitor({
     *         competitorId: "competitorId"
     *     })
     */
    public deleteCompetitor(
        request: Elmo.DeleteCompetitorRequest,
        requestOptions?: CompetitorsClient.RequestOptions,
    ): core.HttpResponsePromise<Elmo.Competitor> {
        return core.HttpResponsePromise.fromPromise(this.__deleteCompetitor(request, requestOptions));
    }

    private async __deleteCompetitor(
        request: Elmo.DeleteCompetitorRequest,
        requestOptions?: CompetitorsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Elmo.Competitor>> {
        const { competitorId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ElmoEnvironment.Default,
                `competitors/${core.url.encodePathParam(competitorId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Elmo.Competitor, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Elmo.BadRequestError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 401:
                    throw new Elmo.UnauthorizedError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 402:
                    throw new Elmo.PaymentRequiredError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 403:
                    throw new Elmo.ForbiddenError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 404:
                    throw new Elmo.NotFoundError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 409:
                    throw new Elmo.ConflictError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 429:
                    throw new Elmo.TooManyRequestsError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 500:
                    throw new Elmo.InternalServerError(_response.error.body as Elmo.Error_, _response.rawResponse);
                default:
                    throw new errors.ElmoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/competitors/{competitorId}",
        );
    }

    /**
     * @param {Elmo.UpdateCompetitorRequest} request
     * @param {CompetitorsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Elmo.BadRequestError}
     * @throws {@link Elmo.UnauthorizedError}
     * @throws {@link Elmo.PaymentRequiredError}
     * @throws {@link Elmo.ForbiddenError}
     * @throws {@link Elmo.NotFoundError}
     * @throws {@link Elmo.ConflictError}
     * @throws {@link Elmo.TooManyRequestsError}
     * @throws {@link Elmo.InternalServerError}
     * @throws {@link errors.ElmoError}
     * @throws {@link errors.ElmoTimeoutError}
     *
     * @example
     *     await client.competitors.updateCompetitor({
     *         competitorId: "competitorId"
     *     })
     */
    public updateCompetitor(
        request: Elmo.UpdateCompetitorRequest,
        requestOptions?: CompetitorsClient.RequestOptions,
    ): core.HttpResponsePromise<Elmo.Competitor> {
        return core.HttpResponsePromise.fromPromise(this.__updateCompetitor(request, requestOptions));
    }

    private async __updateCompetitor(
        request: Elmo.UpdateCompetitorRequest,
        requestOptions?: CompetitorsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Elmo.Competitor>> {
        const { competitorId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ElmoEnvironment.Default,
                `competitors/${core.url.encodePathParam(competitorId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Elmo.Competitor, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Elmo.BadRequestError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 401:
                    throw new Elmo.UnauthorizedError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 402:
                    throw new Elmo.PaymentRequiredError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 403:
                    throw new Elmo.ForbiddenError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 404:
                    throw new Elmo.NotFoundError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 409:
                    throw new Elmo.ConflictError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 429:
                    throw new Elmo.TooManyRequestsError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 500:
                    throw new Elmo.InternalServerError(_response.error.body as Elmo.Error_, _response.rawResponse);
                default:
                    throw new errors.ElmoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/competitors/{competitorId}");
    }
}
