# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.onboarding_suggestion import OnboardingSuggestion
from .raw_client import AsyncRawToolsClient, RawToolsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ToolsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawToolsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawToolsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawToolsClient
        """
        return self._raw_client

    def analyze_brand(
        self,
        *,
        website: str,
        brand_name: typing.Optional[str] = OMIT,
        max_competitors: typing.Optional[int] = OMIT,
        max_prompts: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OnboardingSuggestion:
        """
        Run brand analysis without persisting anything. Returns suggested additional domains, aliases, competitors, and prompts.

        Requires an instance admin key; organization keys receive `403`.

        Parameters
        ----------
        website : str
            Brand's website — a hostname or a full URL. A URL with a path (e.g. https://www.nike.com/golf) is analyzed as given; the returned website is always its domain.

        brand_name : typing.Optional[str]
            Optional brand name hint. If omitted, inferred from the domain.

        max_competitors : typing.Optional[int]
            Maximum number of competitor suggestions. 0 disables competitor generation entirely.

        max_prompts : typing.Optional[int]
            Maximum number of suggested prompts. 0 disables prompt generation entirely.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OnboardingSuggestion
            Brand analysis suggestion

        Examples
        --------
        from elmohq_sdk import Elmo

        client = Elmo(
            token="YOUR_TOKEN",
        )
        client.tools.analyze_brand(
            website="website",
        )
        """
        _response = self._raw_client.analyze_brand(
            website=website,
            brand_name=brand_name,
            max_competitors=max_competitors,
            max_prompts=max_prompts,
            request_options=request_options,
        )
        return _response.data


class AsyncToolsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawToolsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawToolsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawToolsClient
        """
        return self._raw_client

    async def analyze_brand(
        self,
        *,
        website: str,
        brand_name: typing.Optional[str] = OMIT,
        max_competitors: typing.Optional[int] = OMIT,
        max_prompts: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OnboardingSuggestion:
        """
        Run brand analysis without persisting anything. Returns suggested additional domains, aliases, competitors, and prompts.

        Requires an instance admin key; organization keys receive `403`.

        Parameters
        ----------
        website : str
            Brand's website — a hostname or a full URL. A URL with a path (e.g. https://www.nike.com/golf) is analyzed as given; the returned website is always its domain.

        brand_name : typing.Optional[str]
            Optional brand name hint. If omitted, inferred from the domain.

        max_competitors : typing.Optional[int]
            Maximum number of competitor suggestions. 0 disables competitor generation entirely.

        max_prompts : typing.Optional[int]
            Maximum number of suggested prompts. 0 disables prompt generation entirely.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OnboardingSuggestion
            Brand analysis suggestion

        Examples
        --------
        import asyncio

        from elmohq_sdk import AsyncElmo

        client = AsyncElmo(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.tools.analyze_brand(
                website="website",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.analyze_brand(
            website=website,
            brand_name=brand_name,
            max_competitors=max_competitors,
            max_prompts=max_prompts,
            request_options=request_options,
        )
        return _response.data
