packages:
  - "apps/*"
  - "packages/*"
  - "e2e"

blockExoticSubdeps: true
minimumReleaseAge: 5760
minimumReleaseAgeExclude:
  - nitro
  - srvx
  - vite
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 129600
