// This file was auto-generated by Fern from our API Definition.

export interface CreateReportResponse {
    /** Unique identifier for the created report */
    reportId: string;
    /** Initial report status */
    status: CreateReportResponse.Status;
    brandName: string;
    brandAliases: string[];
    brandWebsite: string;
    createdAt: string;
}

export namespace CreateReportResponse {
    /** Initial report status */
    export const Status = {
        Pending: "pending",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
