/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as AuthedAppRouteImport } from './routes/_authed/app'
import { Route as AuthedChoosePlanRouteImport } from './routes/_authed/choose-plan'
import { Route as AuthedReportsRouteImport } from './routes/_authed/reports'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthedAcceptInvitationInvitationIdRouteImport } from './routes/_authed/accept-invitation/$invitationId'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as AuthedAdminToolsRouteImport } from './routes/_authed/admin/tools'
import { Route as AuthedAdminWorkflowsRouteImport } from './routes/_authed/admin/workflows'
import { Route as AuthedAppIndexRouteImport } from './routes/_authed/app/index'
import { Route as AuthedAppOrgRouteImport } from './routes/_authed/app/$org'
import { Route as AuthedReportsIndexRouteImport } from './routes/_authed/reports/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiManifestIndexRouteImport } from './routes/api/manifest/index'
import { Route as ApiOgIndexRouteImport } from './routes/api/og/index'
import { Route as ApiSetupStatusIndexRouteImport } from './routes/api/setup-status/index'
import { Route as AuthedAppOrgIndexRouteImport } from './routes/_authed/app/$org/index'
import { Route as AuthedAppOrgBrandRouteImport } from './routes/_authed/app/$org/$brand'
import { Route as AuthedAppOrgNewRouteImport } from './routes/_authed/app/$org/new'
import { Route as AuthedAppOrgSettingsRouteImport } from './routes/_authed/app/$org/settings'
import { Route as AuthedReportsRenderReportIdRouteImport } from './routes/_authed/reports/render/$reportId'
import { Route as ApiPlausibleEventIndexRouteImport } from './routes/api/plausible/event/index'
import { Route as ApiV1BrandsIndexRouteImport } from './routes/api/v1/brands/index'
import { Route as ApiV1BrandsBrandIdRouteImport } from './routes/api/v1/brands/$brandId'
import { Route as ApiV1CompetitorsIndexRouteImport } from './routes/api/v1/competitors/index'
import { Route as ApiV1CompetitorsCompetitorIdRouteImport } from './routes/api/v1/competitors/$competitorId'
import { Route as ApiV1DocsIndexRouteImport } from './routes/api/v1/docs/index'
import { Route as ApiV1PromptsIndexRouteImport } from './routes/api/v1/prompts/index'
import { Route as ApiV1PromptsPromptIdRouteImport } from './routes/api/v1/prompts/$promptId'
import { Route as ApiV1ReportsIndexRouteImport } from './routes/api/v1/reports/index'
import { Route as ApiV1ReportsReportIdRouteImport } from './routes/api/v1/reports/$reportId'
import { Route as ApiV1ToolsAnalyzeRouteImport } from './routes/api/v1/tools/analyze'
import { Route as AuthedAppOrgBrandIndexRouteImport } from './routes/_authed/app/$org/$brand/index'
import { Route as AuthedAppOrgBrandSplatRouteImport } from './routes/_authed/app/$org/$brand/$'
import { Route as AuthedAppOrgBrandCitationsRouteImport } from './routes/_authed/app/$org/$brand/citations'
import { Route as AuthedAppOrgBrandOpportunitiesRouteImport } from './routes/_authed/app/$org/$brand/opportunities'
import { Route as AuthedAppOrgBrandQueryFanOutRouteImport } from './routes/_authed/app/$org/$brand/query-fan-out'
import { Route as AuthedAppOrgBrandShareOfVoiceRouteImport } from './routes/_authed/app/$org/$brand/share-of-voice'
import { Route as AuthedAppOrgBrandVisibilityRouteImport } from './routes/_authed/app/$org/$brand/visibility'
import { Route as AuthedAppOrgSettingsIndexRouteImport } from './routes/_authed/app/$org/settings/index'
import { Route as AuthedAppOrgSettingsBillingRouteImport } from './routes/_authed/app/$org/settings/billing'
import { Route as AuthedAppOrgSettingsMembersRouteImport } from './routes/_authed/app/$org/settings/members'
import { Route as ApiPlausibleJsScriptIndexRouteImport } from './routes/api/plausible/js/script/index'
import { Route as ApiV1PromptsPromptIdSnapshotRouteImport } from './routes/api/v1/prompts/$promptId/snapshot'
import { Route as AuthedAppOrgBrandPromptsIndexRouteImport } from './routes/_authed/app/$org/$brand/prompts/index'
import { Route as AuthedAppOrgBrandPromptsPromptIdRouteImport } from './routes/_authed/app/$org/$brand/prompts/$promptId'
import { Route as AuthedAppOrgBrandPromptsEditRouteImport } from './routes/_authed/app/$org/$brand/prompts/edit'
import { Route as AuthedAppOrgBrandSettingsIndexRouteImport } from './routes/_authed/app/$org/$brand/settings/index'
import { Route as AuthedAppOrgBrandSettingsBillingRouteImport } from './routes/_authed/app/$org/$brand/settings/billing'
import { Route as AuthedAppOrgBrandSettingsBrandRouteImport } from './routes/_authed/app/$org/$brand/settings/brand'
import { Route as AuthedAppOrgBrandSettingsCompetitorsRouteImport } from './routes/_authed/app/$org/$brand/settings/competitors'
import { Route as AuthedAppOrgBrandSettingsLlmsRouteImport } from './routes/_authed/app/$org/$brand/settings/llms'
import { Route as AuthedAppOrgBrandSettingsMembersRouteImport } from './routes/_authed/app/$org/$brand/settings/members'
import { Route as AuthedAppOrgBrandSettingsPromptsRouteImport } from './routes/_authed/app/$org/$brand/settings/prompts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAppRoute = AuthedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedChoosePlanRoute = AuthedChoosePlanRouteImport.update({
  id: '/choose-plan',
  path: '/choose-plan',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReportsRoute = AuthedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAcceptInvitationInvitationIdRoute =
  AuthedAcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminToolsRoute = AuthedAdminToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminWorkflowsRoute = AuthedAdminWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAppIndexRoute = AuthedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppOrgRoute = AuthedAppOrgRouteImport.update({
  id: '/$org',
  path: '/$org',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedReportsIndexRoute = AuthedReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedReportsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiManifestIndexRoute = ApiManifestIndexRouteImport.update({
  id: '/api/manifest/',
  path: '/api/manifest/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgIndexRoute = ApiOgIndexRouteImport.update({
  id: '/api/og/',
  path: '/api/og/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSetupStatusIndexRoute = ApiSetupStatusIndexRouteImport.update({
  id: '/api/setup-status/',
  path: '/api/setup-status/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAppOrgIndexRoute = AuthedAppOrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAppOrgRoute,
} as any)
const AuthedAppOrgBrandRoute = AuthedAppOrgBrandRouteImport.update({
  id: '/$brand',
  path: '/$brand',
  getParentRoute: () => AuthedAppOrgRoute,
} as any)
const AuthedAppOrgNewRoute = AuthedAppOrgNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedAppOrgRoute,
} as any)
const AuthedAppOrgSettingsRoute = AuthedAppOrgSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedAppOrgRoute,
} as any)
const AuthedReportsRenderReportIdRoute =
  AuthedReportsRenderReportIdRouteImport.update({
    id: '/render/$reportId',
    path: '/render/$reportId',
    getParentRoute: () => AuthedReportsRoute,
  } as any)
const ApiPlausibleEventIndexRoute = ApiPlausibleEventIndexRouteImport.update({
  id: '/api/plausible/event/',
  path: '/api/plausible/event/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BrandsIndexRoute = ApiV1BrandsIndexRouteImport.update({
  id: '/api/v1/brands/',
  path: '/api/v1/brands/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BrandsBrandIdRoute = ApiV1BrandsBrandIdRouteImport.update({
  id: '/api/v1/brands/$brandId',
  path: '/api/v1/brands/$brandId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CompetitorsIndexRoute = ApiV1CompetitorsIndexRouteImport.update({
  id: '/api/v1/competitors/',
  path: '/api/v1/competitors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CompetitorsCompetitorIdRoute =
  ApiV1CompetitorsCompetitorIdRouteImport.update({
    id: '/api/v1/competitors/$competitorId',
    path: '/api/v1/competitors/$competitorId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1DocsIndexRoute = ApiV1DocsIndexRouteImport.update({
  id: '/api/v1/docs/',
  path: '/api/v1/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PromptsIndexRoute = ApiV1PromptsIndexRouteImport.update({
  id: '/api/v1/prompts/',
  path: '/api/v1/prompts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PromptsPromptIdRoute = ApiV1PromptsPromptIdRouteImport.update({
  id: '/api/v1/prompts/$promptId',
  path: '/api/v1/prompts/$promptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ReportsIndexRoute = ApiV1ReportsIndexRouteImport.update({
  id: '/api/v1/reports/',
  path: '/api/v1/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ReportsReportIdRoute = ApiV1ReportsReportIdRouteImport.update({
  id: '/api/v1/reports/$reportId',
  path: '/api/v1/reports/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ToolsAnalyzeRoute = ApiV1ToolsAnalyzeRouteImport.update({
  id: '/api/v1/tools/analyze',
  path: '/api/v1/tools/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAppOrgBrandIndexRoute = AuthedAppOrgBrandIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAppOrgBrandRoute,
} as any)
const AuthedAppOrgBrandSplatRoute = AuthedAppOrgBrandSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthedAppOrgBrandRoute,
} as any)
const AuthedAppOrgBrandCitationsRoute =
  AuthedAppOrgBrandCitationsRouteImport.update({
    id: '/citations',
    path: '/citations',
    getParentRoute: () => AuthedAppOrgBrandRoute,
  } as any)
const AuthedAppOrgBrandOpportunitiesRoute =
  AuthedAppOrgBrandOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => AuthedAppOrgBrandRoute,
  } as any)
const AuthedAppOrgBrandQueryFanOutRoute =
  AuthedAppOrgBrandQueryFanOutRouteImport.update({
    id: '/query-fan-out',
    path: '/query-fan-out',
    getParentRoute: () => AuthedAppOrgBrandRoute,
  } as any)
const AuthedAppOrgBrandShareOfVoiceRoute =
  AuthedAppOrgBrandShareOfVoiceRouteImport.update({
    id: '/share-of-voice',
    path: '/share-of-voice',
    getParentRoute: () => AuthedAppOrgBrandRoute,
  } as any)
const AuthedAppOrgBrandVisibilityRoute =
  AuthedAppOrgBrandVisibilityRouteImport.update({
    id: '/visibility',
    path: '/visibility',
    getParentRoute: () => AuthedAppOrgBrandRoute,
  } as any)
const AuthedAppOrgSettingsIndexRoute =
  AuthedAppOrgSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedAppOrgSettingsRoute,
  } as any)
const AuthedAppOrgSettingsBillingRoute =
  AuthedAppOrgSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthedAppOrgSettingsRoute,
  } as any)
const AuthedAppOrgSettingsMembersRoute =
  AuthedAppOrgSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthedAppOrgSettingsRoute,
  } as any)
const ApiPlausibleJsScriptIndexRoute =
  ApiPlausibleJsScriptIndexRouteImport.update({
    id: '/api/plausible/js/script/',
    path: '/api/plausible/js/script/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1PromptsPromptIdSnapshotRoute =
  ApiV1PromptsPromptIdSnapshotRouteImport.update({
    id: '/snapshot',
    path: '/snapshot',
    getParentRoute: () => ApiV1PromptsPromptIdRoute,
  } as any)
const AuthedAppOrgBrandPromptsIndexRoute =
  AuthedAppOrgBrandPromptsIndexRouteImport.update({
    id: '/prompts/',
    path: '/prompts/',
    getParentRoute: () => AuthedAppOrgBrandRoute,
  } as any)
const AuthedAppOrgBrandPromptsPromptIdRoute =
  AuthedAppOrgBrandPromptsPromptIdRouteImport.update({
    id: '/prompts/$promptId',
    path: '/prompts/$promptId',
    getParentRoute: () => AuthedAppOrgBrandRoute,
  } as any)
const AuthedAppOrgBrandPromptsEditRoute =
  AuthedAppOrgBrandPromptsEditRouteImport.update({
    id: '/prompts/edit',
    path: '/prompts/edit',
    getParentRoute: () => AuthedAppOrgBrandRoute,
  } as any)
const AuthedAppOrgBrandSettingsIndexRoute =
  AuthedAppOrgBrandSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthedAppOrgBrandRoute,
  } as any)
const AuthedAppOrgBrandSettingsBillingRoute =
  AuthedAppOrgBrandSettingsBillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => AuthedAppOrgBrandRoute,
  } as any)
const AuthedAppOrgBrandSettingsBrandRoute =
  AuthedAppOrgBrandSettingsBrandRouteImport.update({
    id: '/settings/brand',
    path: '/settings/brand',
    getParentRoute: () => AuthedAppOrgBrandRoute,
  } as any)
const AuthedAppOrgBrandSettingsCompetitorsRoute =
  AuthedAppOrgBrandSettingsCompetitorsRouteImport.update({
    id: '/settings/competitors',
    path: '/settings/competitors',
    getParentRoute: () => AuthedAppOrgBrandRoute,
  } as any)
const AuthedAppOrgBrandSettingsLlmsRoute =
  AuthedAppOrgBrandSettingsLlmsRouteImport.update({
    id: '/settings/llms',
    path: '/settings/llms',
    getParentRoute: () => AuthedAppOrgBrandRoute,
  } as any)
const AuthedAppOrgBrandSettingsMembersRoute =
  AuthedAppOrgBrandSettingsMembersRouteImport.update({
    id: '/settings/members',
    path: '/settings/members',
    getParentRoute: () => AuthedAppOrgBrandRoute,
  } as any)
const AuthedAppOrgBrandSettingsPromptsRoute =
  AuthedAppOrgBrandSettingsPromptsRouteImport.update({
    id: '/settings/prompts',
    path: '/settings/prompts',
    getParentRoute: () => AuthedAppOrgBrandRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthedAdminRouteWithChildren
  '/app': typeof AuthedAppRouteWithChildren
  '/choose-plan': typeof AuthedChoosePlanRoute
  '/reports': typeof AuthedReportsRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/accept-invitation/$invitationId': typeof AuthedAcceptInvitationInvitationIdRoute
  '/admin/tools': typeof AuthedAdminToolsRoute
  '/admin/workflows': typeof AuthedAdminWorkflowsRoute
  '/app/$org': typeof AuthedAppOrgRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/app/': typeof AuthedAppIndexRoute
  '/reports/': typeof AuthedReportsIndexRoute
  '/api/manifest/': typeof ApiManifestIndexRoute
  '/api/og/': typeof ApiOgIndexRoute
  '/api/setup-status/': typeof ApiSetupStatusIndexRoute
  '/app/$org/$brand': typeof AuthedAppOrgBrandRouteWithChildren
  '/app/$org/new': typeof AuthedAppOrgNewRoute
  '/app/$org/settings': typeof AuthedAppOrgSettingsRouteWithChildren
  '/reports/render/$reportId': typeof AuthedReportsRenderReportIdRoute
  '/api/v1/brands/$brandId': typeof ApiV1BrandsBrandIdRoute
  '/api/v1/competitors/$competitorId': typeof ApiV1CompetitorsCompetitorIdRoute
  '/api/v1/prompts/$promptId': typeof ApiV1PromptsPromptIdRouteWithChildren
  '/api/v1/reports/$reportId': typeof ApiV1ReportsReportIdRoute
  '/api/v1/tools/analyze': typeof ApiV1ToolsAnalyzeRoute
  '/app/$org/': typeof AuthedAppOrgIndexRoute
  '/api/plausible/event/': typeof ApiPlausibleEventIndexRoute
  '/api/v1/brands/': typeof ApiV1BrandsIndexRoute
  '/api/v1/competitors/': typeof ApiV1CompetitorsIndexRoute
  '/api/v1/docs/': typeof ApiV1DocsIndexRoute
  '/api/v1/prompts/': typeof ApiV1PromptsIndexRoute
  '/api/v1/reports/': typeof ApiV1ReportsIndexRoute
  '/app/$org/$brand/$': typeof AuthedAppOrgBrandSplatRoute
  '/app/$org/$brand/citations': typeof AuthedAppOrgBrandCitationsRoute
  '/app/$org/$brand/opportunities': typeof AuthedAppOrgBrandOpportunitiesRoute
  '/app/$org/$brand/query-fan-out': typeof AuthedAppOrgBrandQueryFanOutRoute
  '/app/$org/$brand/share-of-voice': typeof AuthedAppOrgBrandShareOfVoiceRoute
  '/app/$org/$brand/visibility': typeof AuthedAppOrgBrandVisibilityRoute
  '/app/$org/settings/billing': typeof AuthedAppOrgSettingsBillingRoute
  '/app/$org/settings/members': typeof AuthedAppOrgSettingsMembersRoute
  '/api/v1/prompts/$promptId/snapshot': typeof ApiV1PromptsPromptIdSnapshotRoute
  '/app/$org/$brand/': typeof AuthedAppOrgBrandIndexRoute
  '/app/$org/settings/': typeof AuthedAppOrgSettingsIndexRoute
  '/api/plausible/js/script/': typeof ApiPlausibleJsScriptIndexRoute
  '/app/$org/$brand/prompts/$promptId': typeof AuthedAppOrgBrandPromptsPromptIdRoute
  '/app/$org/$brand/prompts/edit': typeof AuthedAppOrgBrandPromptsEditRoute
  '/app/$org/$brand/settings/billing': typeof AuthedAppOrgBrandSettingsBillingRoute
  '/app/$org/$brand/settings/brand': typeof AuthedAppOrgBrandSettingsBrandRoute
  '/app/$org/$brand/settings/competitors': typeof AuthedAppOrgBrandSettingsCompetitorsRoute
  '/app/$org/$brand/settings/llms': typeof AuthedAppOrgBrandSettingsLlmsRoute
  '/app/$org/$brand/settings/members': typeof AuthedAppOrgBrandSettingsMembersRoute
  '/app/$org/$brand/settings/prompts': typeof AuthedAppOrgBrandSettingsPromptsRoute
  '/app/$org/$brand/prompts/': typeof AuthedAppOrgBrandPromptsIndexRoute
  '/app/$org/$brand/settings/': typeof AuthedAppOrgBrandSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/choose-plan': typeof AuthedChoosePlanRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/accept-invitation/$invitationId': typeof AuthedAcceptInvitationInvitationIdRoute
  '/admin/tools': typeof AuthedAdminToolsRoute
  '/admin/workflows': typeof AuthedAdminWorkflowsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/app': typeof AuthedAppIndexRoute
  '/reports': typeof AuthedReportsIndexRoute
  '/api/manifest': typeof ApiManifestIndexRoute
  '/api/og': typeof ApiOgIndexRoute
  '/api/setup-status': typeof ApiSetupStatusIndexRoute
  '/app/$org/new': typeof AuthedAppOrgNewRoute
  '/reports/render/$reportId': typeof AuthedReportsRenderReportIdRoute
  '/api/v1/brands/$brandId': typeof ApiV1BrandsBrandIdRoute
  '/api/v1/competitors/$competitorId': typeof ApiV1CompetitorsCompetitorIdRoute
  '/api/v1/prompts/$promptId': typeof ApiV1PromptsPromptIdRouteWithChildren
  '/api/v1/reports/$reportId': typeof ApiV1ReportsReportIdRoute
  '/api/v1/tools/analyze': typeof ApiV1ToolsAnalyzeRoute
  '/app/$org': typeof AuthedAppOrgIndexRoute
  '/api/plausible/event': typeof ApiPlausibleEventIndexRoute
  '/api/v1/brands': typeof ApiV1BrandsIndexRoute
  '/api/v1/competitors': typeof ApiV1CompetitorsIndexRoute
  '/api/v1/docs': typeof ApiV1DocsIndexRoute
  '/api/v1/prompts': typeof ApiV1PromptsIndexRoute
  '/api/v1/reports': typeof ApiV1ReportsIndexRoute
  '/app/$org/$brand/$': typeof AuthedAppOrgBrandSplatRoute
  '/app/$org/$brand/citations': typeof AuthedAppOrgBrandCitationsRoute
  '/app/$org/$brand/opportunities': typeof AuthedAppOrgBrandOpportunitiesRoute
  '/app/$org/$brand/query-fan-out': typeof AuthedAppOrgBrandQueryFanOutRoute
  '/app/$org/$brand/share-of-voice': typeof AuthedAppOrgBrandShareOfVoiceRoute
  '/app/$org/$brand/visibility': typeof AuthedAppOrgBrandVisibilityRoute
  '/app/$org/settings/billing': typeof AuthedAppOrgSettingsBillingRoute
  '/app/$org/settings/members': typeof AuthedAppOrgSettingsMembersRoute
  '/api/v1/prompts/$promptId/snapshot': typeof ApiV1PromptsPromptIdSnapshotRoute
  '/app/$org/$brand': typeof AuthedAppOrgBrandIndexRoute
  '/app/$org/settings': typeof AuthedAppOrgSettingsIndexRoute
  '/api/plausible/js/script': typeof ApiPlausibleJsScriptIndexRoute
  '/app/$org/$brand/prompts/$promptId': typeof AuthedAppOrgBrandPromptsPromptIdRoute
  '/app/$org/$brand/prompts/edit': typeof AuthedAppOrgBrandPromptsEditRoute
  '/app/$org/$brand/settings/billing': typeof AuthedAppOrgBrandSettingsBillingRoute
  '/app/$org/$brand/settings/brand': typeof AuthedAppOrgBrandSettingsBrandRoute
  '/app/$org/$brand/settings/competitors': typeof AuthedAppOrgBrandSettingsCompetitorsRoute
  '/app/$org/$brand/settings/llms': typeof AuthedAppOrgBrandSettingsLlmsRoute
  '/app/$org/$brand/settings/members': typeof AuthedAppOrgBrandSettingsMembersRoute
  '/app/$org/$brand/settings/prompts': typeof AuthedAppOrgBrandSettingsPromptsRoute
  '/app/$org/$brand/prompts': typeof AuthedAppOrgBrandPromptsIndexRoute
  '/app/$org/$brand/settings': typeof AuthedAppOrgBrandSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/admin': typeof AuthedAdminRouteWithChildren
  '/_authed/app': typeof AuthedAppRouteWithChildren
  '/_authed/choose-plan': typeof AuthedChoosePlanRoute
  '/_authed/reports': typeof AuthedReportsRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_authed/accept-invitation/$invitationId': typeof AuthedAcceptInvitationInvitationIdRoute
  '/_authed/admin/tools': typeof AuthedAdminToolsRoute
  '/_authed/admin/workflows': typeof AuthedAdminWorkflowsRoute
  '/_authed/app/$org': typeof AuthedAppOrgRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/app/': typeof AuthedAppIndexRoute
  '/_authed/reports/': typeof AuthedReportsIndexRoute
  '/api/manifest/': typeof ApiManifestIndexRoute
  '/api/og/': typeof ApiOgIndexRoute
  '/api/setup-status/': typeof ApiSetupStatusIndexRoute
  '/_authed/app/$org/$brand': typeof AuthedAppOrgBrandRouteWithChildren
  '/_authed/app/$org/new': typeof AuthedAppOrgNewRoute
  '/_authed/app/$org/settings': typeof AuthedAppOrgSettingsRouteWithChildren
  '/_authed/reports/render/$reportId': typeof AuthedReportsRenderReportIdRoute
  '/api/v1/brands/$brandId': typeof ApiV1BrandsBrandIdRoute
  '/api/v1/competitors/$competitorId': typeof ApiV1CompetitorsCompetitorIdRoute
  '/api/v1/prompts/$promptId': typeof ApiV1PromptsPromptIdRouteWithChildren
  '/api/v1/reports/$reportId': typeof ApiV1ReportsReportIdRoute
  '/api/v1/tools/analyze': typeof ApiV1ToolsAnalyzeRoute
  '/_authed/app/$org/': typeof AuthedAppOrgIndexRoute
  '/api/plausible/event/': typeof ApiPlausibleEventIndexRoute
  '/api/v1/brands/': typeof ApiV1BrandsIndexRoute
  '/api/v1/competitors/': typeof ApiV1CompetitorsIndexRoute
  '/api/v1/docs/': typeof ApiV1DocsIndexRoute
  '/api/v1/prompts/': typeof ApiV1PromptsIndexRoute
  '/api/v1/reports/': typeof ApiV1ReportsIndexRoute
  '/_authed/app/$org/$brand/$': typeof AuthedAppOrgBrandSplatRoute
  '/_authed/app/$org/$brand/citations': typeof AuthedAppOrgBrandCitationsRoute
  '/_authed/app/$org/$brand/opportunities': typeof AuthedAppOrgBrandOpportunitiesRoute
  '/_authed/app/$org/$brand/query-fan-out': typeof AuthedAppOrgBrandQueryFanOutRoute
  '/_authed/app/$org/$brand/share-of-voice': typeof AuthedAppOrgBrandShareOfVoiceRoute
  '/_authed/app/$org/$brand/visibility': typeof AuthedAppOrgBrandVisibilityRoute
  '/_authed/app/$org/settings/billing': typeof AuthedAppOrgSettingsBillingRoute
  '/_authed/app/$org/settings/members': typeof AuthedAppOrgSettingsMembersRoute
  '/api/v1/prompts/$promptId/snapshot': typeof ApiV1PromptsPromptIdSnapshotRoute
  '/_authed/app/$org/$brand/': typeof AuthedAppOrgBrandIndexRoute
  '/_authed/app/$org/settings/': typeof AuthedAppOrgSettingsIndexRoute
  '/api/plausible/js/script/': typeof ApiPlausibleJsScriptIndexRoute
  '/_authed/app/$org/$brand/prompts/$promptId': typeof AuthedAppOrgBrandPromptsPromptIdRoute
  '/_authed/app/$org/$brand/prompts/edit': typeof AuthedAppOrgBrandPromptsEditRoute
  '/_authed/app/$org/$brand/settings/billing': typeof AuthedAppOrgBrandSettingsBillingRoute
  '/_authed/app/$org/$brand/settings/brand': typeof AuthedAppOrgBrandSettingsBrandRoute
  '/_authed/app/$org/$brand/settings/competitors': typeof AuthedAppOrgBrandSettingsCompetitorsRoute
  '/_authed/app/$org/$brand/settings/llms': typeof AuthedAppOrgBrandSettingsLlmsRoute
  '/_authed/app/$org/$brand/settings/members': typeof AuthedAppOrgBrandSettingsMembersRoute
  '/_authed/app/$org/$brand/settings/prompts': typeof AuthedAppOrgBrandSettingsPromptsRoute
  '/_authed/app/$org/$brand/prompts/': typeof AuthedAppOrgBrandPromptsIndexRoute
  '/_authed/app/$org/$brand/settings/': typeof AuthedAppOrgBrandSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/choose-plan'
    | '/reports'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
    | '/auth/reset-password'
    | '/accept-invitation/$invitationId'
    | '/admin/tools'
    | '/admin/workflows'
    | '/app/$org'
    | '/api/auth/$'
    | '/admin/'
    | '/app/'
    | '/reports/'
    | '/api/manifest/'
    | '/api/og/'
    | '/api/setup-status/'
    | '/app/$org/$brand'
    | '/app/$org/new'
    | '/app/$org/settings'
    | '/reports/render/$reportId'
    | '/api/v1/brands/$brandId'
    | '/api/v1/competitors/$competitorId'
    | '/api/v1/prompts/$promptId'
    | '/api/v1/reports/$reportId'
    | '/api/v1/tools/analyze'
    | '/app/$org/'
    | '/api/plausible/event/'
    | '/api/v1/brands/'
    | '/api/v1/competitors/'
    | '/api/v1/docs/'
    | '/api/v1/prompts/'
    | '/api/v1/reports/'
    | '/app/$org/$brand/$'
    | '/app/$org/$brand/citations'
    | '/app/$org/$brand/opportunities'
    | '/app/$org/$brand/query-fan-out'
    | '/app/$org/$brand/share-of-voice'
    | '/app/$org/$brand/visibility'
    | '/app/$org/settings/billing'
    | '/app/$org/settings/members'
    | '/api/v1/prompts/$promptId/snapshot'
    | '/app/$org/$brand/'
    | '/app/$org/settings/'
    | '/api/plausible/js/script/'
    | '/app/$org/$brand/prompts/$promptId'
    | '/app/$org/$brand/prompts/edit'
    | '/app/$org/$brand/settings/billing'
    | '/app/$org/$brand/settings/brand'
    | '/app/$org/$brand/settings/competitors'
    | '/app/$org/$brand/settings/llms'
    | '/app/$org/$brand/settings/members'
    | '/app/$org/$brand/settings/prompts'
    | '/app/$org/$brand/prompts/'
    | '/app/$org/$brand/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/choose-plan'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
    | '/auth/reset-password'
    | '/accept-invitation/$invitationId'
    | '/admin/tools'
    | '/admin/workflows'
    | '/api/auth/$'
    | '/admin'
    | '/app'
    | '/reports'
    | '/api/manifest'
    | '/api/og'
    | '/api/setup-status'
    | '/app/$org/new'
    | '/reports/render/$reportId'
    | '/api/v1/brands/$brandId'
    | '/api/v1/competitors/$competitorId'
    | '/api/v1/prompts/$promptId'
    | '/api/v1/reports/$reportId'
    | '/api/v1/tools/analyze'
    | '/app/$org'
    | '/api/plausible/event'
    | '/api/v1/brands'
    | '/api/v1/competitors'
    | '/api/v1/docs'
    | '/api/v1/prompts'
    | '/api/v1/reports'
    | '/app/$org/$brand/$'
    | '/app/$org/$brand/citations'
    | '/app/$org/$brand/opportunities'
    | '/app/$org/$brand/query-fan-out'
    | '/app/$org/$brand/share-of-voice'
    | '/app/$org/$brand/visibility'
    | '/app/$org/settings/billing'
    | '/app/$org/settings/members'
    | '/api/v1/prompts/$promptId/snapshot'
    | '/app/$org/$brand'
    | '/app/$org/settings'
    | '/api/plausible/js/script'
    | '/app/$org/$brand/prompts/$promptId'
    | '/app/$org/$brand/prompts/edit'
    | '/app/$org/$brand/settings/billing'
    | '/app/$org/$brand/settings/brand'
    | '/app/$org/$brand/settings/competitors'
    | '/app/$org/$brand/settings/llms'
    | '/app/$org/$brand/settings/members'
    | '/app/$org/$brand/settings/prompts'
    | '/app/$org/$brand/prompts'
    | '/app/$org/$brand/settings'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/admin'
    | '/_authed/app'
    | '/_authed/choose-plan'
    | '/_authed/reports'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
    | '/auth/reset-password'
    | '/_authed/accept-invitation/$invitationId'
    | '/_authed/admin/tools'
    | '/_authed/admin/workflows'
    | '/_authed/app/$org'
    | '/api/auth/$'
    | '/_authed/admin/'
    | '/_authed/app/'
    | '/_authed/reports/'
    | '/api/manifest/'
    | '/api/og/'
    | '/api/setup-status/'
    | '/_authed/app/$org/$brand'
    | '/_authed/app/$org/new'
    | '/_authed/app/$org/settings'
    | '/_authed/reports/render/$reportId'
    | '/api/v1/brands/$brandId'
    | '/api/v1/competitors/$competitorId'
    | '/api/v1/prompts/$promptId'
    | '/api/v1/reports/$reportId'
    | '/api/v1/tools/analyze'
    | '/_authed/app/$org/'
    | '/api/plausible/event/'
    | '/api/v1/brands/'
    | '/api/v1/competitors/'
    | '/api/v1/docs/'
    | '/api/v1/prompts/'
    | '/api/v1/reports/'
    | '/_authed/app/$org/$brand/$'
    | '/_authed/app/$org/$brand/citations'
    | '/_authed/app/$org/$brand/opportunities'
    | '/_authed/app/$org/$brand/query-fan-out'
    | '/_authed/app/$org/$brand/share-of-voice'
    | '/_authed/app/$org/$brand/visibility'
    | '/_authed/app/$org/settings/billing'
    | '/_authed/app/$org/settings/members'
    | '/api/v1/prompts/$promptId/snapshot'
    | '/_authed/app/$org/$brand/'
    | '/_authed/app/$org/settings/'
    | '/api/plausible/js/script/'
    | '/_authed/app/$org/$brand/prompts/$promptId'
    | '/_authed/app/$org/$brand/prompts/edit'
    | '/_authed/app/$org/$brand/settings/billing'
    | '/_authed/app/$org/$brand/settings/brand'
    | '/_authed/app/$org/$brand/settings/competitors'
    | '/_authed/app/$org/$brand/settings/llms'
    | '/_authed/app/$org/$brand/settings/members'
    | '/_authed/app/$org/$brand/settings/prompts'
    | '/_authed/app/$org/$brand/prompts/'
    | '/_authed/app/$org/$brand/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiManifestIndexRoute: typeof ApiManifestIndexRoute
  ApiOgIndexRoute: typeof ApiOgIndexRoute
  ApiSetupStatusIndexRoute: typeof ApiSetupStatusIndexRoute
  ApiV1BrandsBrandIdRoute: typeof ApiV1BrandsBrandIdRoute
  ApiV1CompetitorsCompetitorIdRoute: typeof ApiV1CompetitorsCompetitorIdRoute
  ApiV1PromptsPromptIdRoute: typeof ApiV1PromptsPromptIdRouteWithChildren
  ApiV1ReportsReportIdRoute: typeof ApiV1ReportsReportIdRoute
  ApiV1ToolsAnalyzeRoute: typeof ApiV1ToolsAnalyzeRoute
  ApiPlausibleEventIndexRoute: typeof ApiPlausibleEventIndexRoute
  ApiV1BrandsIndexRoute: typeof ApiV1BrandsIndexRoute
  ApiV1CompetitorsIndexRoute: typeof ApiV1CompetitorsIndexRoute
  ApiV1DocsIndexRoute: typeof ApiV1DocsIndexRoute
  ApiV1PromptsIndexRoute: typeof ApiV1PromptsIndexRoute
  ApiV1ReportsIndexRoute: typeof ApiV1ReportsIndexRoute
  ApiPlausibleJsScriptIndexRoute: typeof ApiPlausibleJsScriptIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/app': {
      id: '/_authed/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthedAppRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/choose-plan': {
      id: '/_authed/choose-plan'
      path: '/choose-plan'
      fullPath: '/choose-plan'
      preLoaderRoute: typeof AuthedChoosePlanRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reports': {
      id: '/_authed/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthedReportsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/accept-invitation/$invitationId': {
      id: '/_authed/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AuthedAcceptInvitationInvitationIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/tools': {
      id: '/_authed/admin/tools'
      path: '/tools'
      fullPath: '/admin/tools'
      preLoaderRoute: typeof AuthedAdminToolsRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/workflows': {
      id: '/_authed/admin/workflows'
      path: '/workflows'
      fullPath: '/admin/workflows'
      preLoaderRoute: typeof AuthedAdminWorkflowsRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/app/': {
      id: '/_authed/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthedAppIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/app/$org': {
      id: '/_authed/app/$org'
      path: '/$org'
      fullPath: '/app/$org'
      preLoaderRoute: typeof AuthedAppOrgRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/reports/': {
      id: '/_authed/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthedReportsIndexRouteImport
      parentRoute: typeof AuthedReportsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/manifest/': {
      id: '/api/manifest/'
      path: '/api/manifest'
      fullPath: '/api/manifest/'
      preLoaderRoute: typeof ApiManifestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/': {
      id: '/api/og/'
      path: '/api/og'
      fullPath: '/api/og/'
      preLoaderRoute: typeof ApiOgIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/setup-status/': {
      id: '/api/setup-status/'
      path: '/api/setup-status'
      fullPath: '/api/setup-status/'
      preLoaderRoute: typeof ApiSetupStatusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/app/$org/': {
      id: '/_authed/app/$org/'
      path: '/'
      fullPath: '/app/$org/'
      preLoaderRoute: typeof AuthedAppOrgIndexRouteImport
      parentRoute: typeof AuthedAppOrgRoute
    }
    '/_authed/app/$org/$brand': {
      id: '/_authed/app/$org/$brand'
      path: '/$brand'
      fullPath: '/app/$org/$brand'
      preLoaderRoute: typeof AuthedAppOrgBrandRouteImport
      parentRoute: typeof AuthedAppOrgRoute
    }
    '/_authed/app/$org/new': {
      id: '/_authed/app/$org/new'
      path: '/new'
      fullPath: '/app/$org/new'
      preLoaderRoute: typeof AuthedAppOrgNewRouteImport
      parentRoute: typeof AuthedAppOrgRoute
    }
    '/_authed/app/$org/settings': {
      id: '/_authed/app/$org/settings'
      path: '/settings'
      fullPath: '/app/$org/settings'
      preLoaderRoute: typeof AuthedAppOrgSettingsRouteImport
      parentRoute: typeof AuthedAppOrgRoute
    }
    '/_authed/reports/render/$reportId': {
      id: '/_authed/reports/render/$reportId'
      path: '/render/$reportId'
      fullPath: '/reports/render/$reportId'
      preLoaderRoute: typeof AuthedReportsRenderReportIdRouteImport
      parentRoute: typeof AuthedReportsRoute
    }
    '/api/plausible/event/': {
      id: '/api/plausible/event/'
      path: '/api/plausible/event'
      fullPath: '/api/plausible/event/'
      preLoaderRoute: typeof ApiPlausibleEventIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/brands/': {
      id: '/api/v1/brands/'
      path: '/api/v1/brands'
      fullPath: '/api/v1/brands/'
      preLoaderRoute: typeof ApiV1BrandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/brands/$brandId': {
      id: '/api/v1/brands/$brandId'
      path: '/api/v1/brands/$brandId'
      fullPath: '/api/v1/brands/$brandId'
      preLoaderRoute: typeof ApiV1BrandsBrandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/competitors/': {
      id: '/api/v1/competitors/'
      path: '/api/v1/competitors'
      fullPath: '/api/v1/competitors/'
      preLoaderRoute: typeof ApiV1CompetitorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/competitors/$competitorId': {
      id: '/api/v1/competitors/$competitorId'
      path: '/api/v1/competitors/$competitorId'
      fullPath: '/api/v1/competitors/$competitorId'
      preLoaderRoute: typeof ApiV1CompetitorsCompetitorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/docs/': {
      id: '/api/v1/docs/'
      path: '/api/v1/docs'
      fullPath: '/api/v1/docs/'
      preLoaderRoute: typeof ApiV1DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/prompts/': {
      id: '/api/v1/prompts/'
      path: '/api/v1/prompts'
      fullPath: '/api/v1/prompts/'
      preLoaderRoute: typeof ApiV1PromptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/prompts/$promptId': {
      id: '/api/v1/prompts/$promptId'
      path: '/api/v1/prompts/$promptId'
      fullPath: '/api/v1/prompts/$promptId'
      preLoaderRoute: typeof ApiV1PromptsPromptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/reports/': {
      id: '/api/v1/reports/'
      path: '/api/v1/reports'
      fullPath: '/api/v1/reports/'
      preLoaderRoute: typeof ApiV1ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/reports/$reportId': {
      id: '/api/v1/reports/$reportId'
      path: '/api/v1/reports/$reportId'
      fullPath: '/api/v1/reports/$reportId'
      preLoaderRoute: typeof ApiV1ReportsReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/tools/analyze': {
      id: '/api/v1/tools/analyze'
      path: '/api/v1/tools/analyze'
      fullPath: '/api/v1/tools/analyze'
      preLoaderRoute: typeof ApiV1ToolsAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/app/$org/$brand/': {
      id: '/_authed/app/$org/$brand/'
      path: '/'
      fullPath: '/app/$org/$brand/'
      preLoaderRoute: typeof AuthedAppOrgBrandIndexRouteImport
      parentRoute: typeof AuthedAppOrgBrandRoute
    }
    '/_authed/app/$org/$brand/$': {
      id: '/_authed/app/$org/$brand/$'
      path: '/$'
      fullPath: '/app/$org/$brand/$'
      preLoaderRoute: typeof AuthedAppOrgBrandSplatRouteImport
      parentRoute: typeof AuthedAppOrgBrandRoute
    }
    '/_authed/app/$org/$brand/citations': {
      id: '/_authed/app/$org/$brand/citations'
      path: '/citations'
      fullPath: '/app/$org/$brand/citations'
      preLoaderRoute: typeof AuthedAppOrgBrandCitationsRouteImport
      parentRoute: typeof AuthedAppOrgBrandRoute
    }
    '/_authed/app/$org/$brand/opportunities': {
      id: '/_authed/app/$org/$brand/opportunities'
      path: '/opportunities'
      fullPath: '/app/$org/$brand/opportunities'
      preLoaderRoute: typeof AuthedAppOrgBrandOpportunitiesRouteImport
      parentRoute: typeof AuthedAppOrgBrandRoute
    }
    '/_authed/app/$org/$brand/query-fan-out': {
      id: '/_authed/app/$org/$brand/query-fan-out'
      path: '/query-fan-out'
      fullPath: '/app/$org/$brand/query-fan-out'
      preLoaderRoute: typeof AuthedAppOrgBrandQueryFanOutRouteImport
      parentRoute: typeof AuthedAppOrgBrandRoute
    }
    '/_authed/app/$org/$brand/share-of-voice': {
      id: '/_authed/app/$org/$brand/share-of-voice'
      path: '/share-of-voice'
      fullPath: '/app/$org/$brand/share-of-voice'
      preLoaderRoute: typeof AuthedAppOrgBrandShareOfVoiceRouteImport
      parentRoute: typeof AuthedAppOrgBrandRoute
    }
    '/_authed/app/$org/$brand/visibility': {
      id: '/_authed/app/$org/$brand/visibility'
      path: '/visibility'
      fullPath: '/app/$org/$brand/visibility'
      preLoaderRoute: typeof AuthedAppOrgBrandVisibilityRouteImport
      parentRoute: typeof AuthedAppOrgBrandRoute
    }
    '/_authed/app/$org/settings/': {
      id: '/_authed/app/$org/settings/'
      path: '/'
      fullPath: '/app/$org/settings/'
      preLoaderRoute: typeof AuthedAppOrgSettingsIndexRouteImport
      parentRoute: typeof AuthedAppOrgSettingsRoute
    }
    '/_authed/app/$org/settings/billing': {
      id: '/_authed/app/$org/settings/billing'
      path: '/billing'
      fullPath: '/app/$org/settings/billing'
      preLoaderRoute: typeof AuthedAppOrgSettingsBillingRouteImport
      parentRoute: typeof AuthedAppOrgSettingsRoute
    }
    '/_authed/app/$org/settings/members': {
      id: '/_authed/app/$org/settings/members'
      path: '/members'
      fullPath: '/app/$org/settings/members'
      preLoaderRoute: typeof AuthedAppOrgSettingsMembersRouteImport
      parentRoute: typeof AuthedAppOrgSettingsRoute
    }
    '/api/plausible/js/script/': {
      id: '/api/plausible/js/script/'
      path: '/api/plausible/js/script'
      fullPath: '/api/plausible/js/script/'
      preLoaderRoute: typeof ApiPlausibleJsScriptIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/prompts/$promptId/snapshot': {
      id: '/api/v1/prompts/$promptId/snapshot'
      path: '/snapshot'
      fullPath: '/api/v1/prompts/$promptId/snapshot'
      preLoaderRoute: typeof ApiV1PromptsPromptIdSnapshotRouteImport
      parentRoute: typeof ApiV1PromptsPromptIdRoute
    }
    '/_authed/app/$org/$brand/prompts/': {
      id: '/_authed/app/$org/$brand/prompts/'
      path: '/prompts'
      fullPath: '/app/$org/$brand/prompts/'
      preLoaderRoute: typeof AuthedAppOrgBrandPromptsIndexRouteImport
      parentRoute: typeof AuthedAppOrgBrandRoute
    }
    '/_authed/app/$org/$brand/prompts/$promptId': {
      id: '/_authed/app/$org/$brand/prompts/$promptId'
      path: '/prompts/$promptId'
      fullPath: '/app/$org/$brand/prompts/$promptId'
      preLoaderRoute: typeof AuthedAppOrgBrandPromptsPromptIdRouteImport
      parentRoute: typeof AuthedAppOrgBrandRoute
    }
    '/_authed/app/$org/$brand/prompts/edit': {
      id: '/_authed/app/$org/$brand/prompts/edit'
      path: '/prompts/edit'
      fullPath: '/app/$org/$brand/prompts/edit'
      preLoaderRoute: typeof AuthedAppOrgBrandPromptsEditRouteImport
      parentRoute: typeof AuthedAppOrgBrandRoute
    }
    '/_authed/app/$org/$brand/settings/': {
      id: '/_authed/app/$org/$brand/settings/'
      path: '/settings'
      fullPath: '/app/$org/$brand/settings/'
      preLoaderRoute: typeof AuthedAppOrgBrandSettingsIndexRouteImport
      parentRoute: typeof AuthedAppOrgBrandRoute
    }
    '/_authed/app/$org/$brand/settings/billing': {
      id: '/_authed/app/$org/$brand/settings/billing'
      path: '/settings/billing'
      fullPath: '/app/$org/$brand/settings/billing'
      preLoaderRoute: typeof AuthedAppOrgBrandSettingsBillingRouteImport
      parentRoute: typeof AuthedAppOrgBrandRoute
    }
    '/_authed/app/$org/$brand/settings/brand': {
      id: '/_authed/app/$org/$brand/settings/brand'
      path: '/settings/brand'
      fullPath: '/app/$org/$brand/settings/brand'
      preLoaderRoute: typeof AuthedAppOrgBrandSettingsBrandRouteImport
      parentRoute: typeof AuthedAppOrgBrandRoute
    }
    '/_authed/app/$org/$brand/settings/competitors': {
      id: '/_authed/app/$org/$brand/settings/competitors'
      path: '/settings/competitors'
      fullPath: '/app/$org/$brand/settings/competitors'
      preLoaderRoute: typeof AuthedAppOrgBrandSettingsCompetitorsRouteImport
      parentRoute: typeof AuthedAppOrgBrandRoute
    }
    '/_authed/app/$org/$brand/settings/llms': {
      id: '/_authed/app/$org/$brand/settings/llms'
      path: '/settings/llms'
      fullPath: '/app/$org/$brand/settings/llms'
      preLoaderRoute: typeof AuthedAppOrgBrandSettingsLlmsRouteImport
      parentRoute: typeof AuthedAppOrgBrandRoute
    }
    '/_authed/app/$org/$brand/settings/members': {
      id: '/_authed/app/$org/$brand/settings/members'
      path: '/settings/members'
      fullPath: '/app/$org/$brand/settings/members'
      preLoaderRoute: typeof AuthedAppOrgBrandSettingsMembersRouteImport
      parentRoute: typeof AuthedAppOrgBrandRoute
    }
    '/_authed/app/$org/$brand/settings/prompts': {
      id: '/_authed/app/$org/$brand/settings/prompts'
      path: '/settings/prompts'
      fullPath: '/app/$org/$brand/settings/prompts'
      preLoaderRoute: typeof AuthedAppOrgBrandSettingsPromptsRouteImport
      parentRoute: typeof AuthedAppOrgBrandRoute
    }
  }
}

interface AuthedAdminRouteChildren {
  AuthedAdminToolsRoute: typeof AuthedAdminToolsRoute
  AuthedAdminWorkflowsRoute: typeof AuthedAdminWorkflowsRoute
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminToolsRoute: AuthedAdminToolsRoute,
  AuthedAdminWorkflowsRoute: AuthedAdminWorkflowsRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedAppOrgBrandRouteChildren {
  AuthedAppOrgBrandSplatRoute: typeof AuthedAppOrgBrandSplatRoute
  AuthedAppOrgBrandCitationsRoute: typeof AuthedAppOrgBrandCitationsRoute
  AuthedAppOrgBrandOpportunitiesRoute: typeof AuthedAppOrgBrandOpportunitiesRoute
  AuthedAppOrgBrandQueryFanOutRoute: typeof AuthedAppOrgBrandQueryFanOutRoute
  AuthedAppOrgBrandShareOfVoiceRoute: typeof AuthedAppOrgBrandShareOfVoiceRoute
  AuthedAppOrgBrandVisibilityRoute: typeof AuthedAppOrgBrandVisibilityRoute
  AuthedAppOrgBrandIndexRoute: typeof AuthedAppOrgBrandIndexRoute
  AuthedAppOrgBrandPromptsPromptIdRoute: typeof AuthedAppOrgBrandPromptsPromptIdRoute
  AuthedAppOrgBrandPromptsEditRoute: typeof AuthedAppOrgBrandPromptsEditRoute
  AuthedAppOrgBrandSettingsBillingRoute: typeof AuthedAppOrgBrandSettingsBillingRoute
  AuthedAppOrgBrandSettingsBrandRoute: typeof AuthedAppOrgBrandSettingsBrandRoute
  AuthedAppOrgBrandSettingsCompetitorsRoute: typeof AuthedAppOrgBrandSettingsCompetitorsRoute
  AuthedAppOrgBrandSettingsLlmsRoute: typeof AuthedAppOrgBrandSettingsLlmsRoute
  AuthedAppOrgBrandSettingsMembersRoute: typeof AuthedAppOrgBrandSettingsMembersRoute
  AuthedAppOrgBrandSettingsPromptsRoute: typeof AuthedAppOrgBrandSettingsPromptsRoute
  AuthedAppOrgBrandPromptsIndexRoute: typeof AuthedAppOrgBrandPromptsIndexRoute
  AuthedAppOrgBrandSettingsIndexRoute: typeof AuthedAppOrgBrandSettingsIndexRoute
}

const AuthedAppOrgBrandRouteChildren: AuthedAppOrgBrandRouteChildren = {
  AuthedAppOrgBrandSplatRoute: AuthedAppOrgBrandSplatRoute,
  AuthedAppOrgBrandCitationsRoute: AuthedAppOrgBrandCitationsRoute,
  AuthedAppOrgBrandOpportunitiesRoute: AuthedAppOrgBrandOpportunitiesRoute,
  AuthedAppOrgBrandQueryFanOutRoute: AuthedAppOrgBrandQueryFanOutRoute,
  AuthedAppOrgBrandShareOfVoiceRoute: AuthedAppOrgBrandShareOfVoiceRoute,
  AuthedAppOrgBrandVisibilityRoute: AuthedAppOrgBrandVisibilityRoute,
  AuthedAppOrgBrandIndexRoute: AuthedAppOrgBrandIndexRoute,
  AuthedAppOrgBrandPromptsPromptIdRoute: AuthedAppOrgBrandPromptsPromptIdRoute,
  AuthedAppOrgBrandPromptsEditRoute: AuthedAppOrgBrandPromptsEditRoute,
  AuthedAppOrgBrandSettingsBillingRoute: AuthedAppOrgBrandSettingsBillingRoute,
  AuthedAppOrgBrandSettingsBrandRoute: AuthedAppOrgBrandSettingsBrandRoute,
  AuthedAppOrgBrandSettingsCompetitorsRoute:
    AuthedAppOrgBrandSettingsCompetitorsRoute,
  AuthedAppOrgBrandSettingsLlmsRoute: AuthedAppOrgBrandSettingsLlmsRoute,
  AuthedAppOrgBrandSettingsMembersRoute: AuthedAppOrgBrandSettingsMembersRoute,
  AuthedAppOrgBrandSettingsPromptsRoute: AuthedAppOrgBrandSettingsPromptsRoute,
  AuthedAppOrgBrandPromptsIndexRoute: AuthedAppOrgBrandPromptsIndexRoute,
  AuthedAppOrgBrandSettingsIndexRoute: AuthedAppOrgBrandSettingsIndexRoute,
}

const AuthedAppOrgBrandRouteWithChildren =
  AuthedAppOrgBrandRoute._addFileChildren(AuthedAppOrgBrandRouteChildren)

interface AuthedAppOrgSettingsRouteChildren {
  AuthedAppOrgSettingsBillingRoute: typeof AuthedAppOrgSettingsBillingRoute
  AuthedAppOrgSettingsMembersRoute: typeof AuthedAppOrgSettingsMembersRoute
  AuthedAppOrgSettingsIndexRoute: typeof AuthedAppOrgSettingsIndexRoute
}

const AuthedAppOrgSettingsRouteChildren: AuthedAppOrgSettingsRouteChildren = {
  AuthedAppOrgSettingsBillingRoute: AuthedAppOrgSettingsBillingRoute,
  AuthedAppOrgSettingsMembersRoute: AuthedAppOrgSettingsMembersRoute,
  AuthedAppOrgSettingsIndexRoute: AuthedAppOrgSettingsIndexRoute,
}

const AuthedAppOrgSettingsRouteWithChildren =
  AuthedAppOrgSettingsRoute._addFileChildren(AuthedAppOrgSettingsRouteChildren)

interface AuthedAppOrgRouteChildren {
  AuthedAppOrgBrandRoute: typeof AuthedAppOrgBrandRouteWithChildren
  AuthedAppOrgNewRoute: typeof AuthedAppOrgNewRoute
  AuthedAppOrgSettingsRoute: typeof AuthedAppOrgSettingsRouteWithChildren
  AuthedAppOrgIndexRoute: typeof AuthedAppOrgIndexRoute
}

const AuthedAppOrgRouteChildren: AuthedAppOrgRouteChildren = {
  AuthedAppOrgBrandRoute: AuthedAppOrgBrandRouteWithChildren,
  AuthedAppOrgNewRoute: AuthedAppOrgNewRoute,
  AuthedAppOrgSettingsRoute: AuthedAppOrgSettingsRouteWithChildren,
  AuthedAppOrgIndexRoute: AuthedAppOrgIndexRoute,
}

const AuthedAppOrgRouteWithChildren = AuthedAppOrgRoute._addFileChildren(
  AuthedAppOrgRouteChildren,
)

interface AuthedAppRouteChildren {
  AuthedAppOrgRoute: typeof AuthedAppOrgRouteWithChildren
  AuthedAppIndexRoute: typeof AuthedAppIndexRoute
}

const AuthedAppRouteChildren: AuthedAppRouteChildren = {
  AuthedAppOrgRoute: AuthedAppOrgRouteWithChildren,
  AuthedAppIndexRoute: AuthedAppIndexRoute,
}

const AuthedAppRouteWithChildren = AuthedAppRoute._addFileChildren(
  AuthedAppRouteChildren,
)

interface AuthedReportsRouteChildren {
  AuthedReportsIndexRoute: typeof AuthedReportsIndexRoute
  AuthedReportsRenderReportIdRoute: typeof AuthedReportsRenderReportIdRoute
}

const AuthedReportsRouteChildren: AuthedReportsRouteChildren = {
  AuthedReportsIndexRoute: AuthedReportsIndexRoute,
  AuthedReportsRenderReportIdRoute: AuthedReportsRenderReportIdRoute,
}

const AuthedReportsRouteWithChildren = AuthedReportsRoute._addFileChildren(
  AuthedReportsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AuthedAppRoute: typeof AuthedAppRouteWithChildren
  AuthedChoosePlanRoute: typeof AuthedChoosePlanRoute
  AuthedReportsRoute: typeof AuthedReportsRouteWithChildren
  AuthedAcceptInvitationInvitationIdRoute: typeof AuthedAcceptInvitationInvitationIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedAppRoute: AuthedAppRouteWithChildren,
  AuthedChoosePlanRoute: AuthedChoosePlanRoute,
  AuthedReportsRoute: AuthedReportsRouteWithChildren,
  AuthedAcceptInvitationInvitationIdRoute:
    AuthedAcceptInvitationInvitationIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface ApiV1PromptsPromptIdRouteChildren {
  ApiV1PromptsPromptIdSnapshotRoute: typeof ApiV1PromptsPromptIdSnapshotRoute
}

const ApiV1PromptsPromptIdRouteChildren: ApiV1PromptsPromptIdRouteChildren = {
  ApiV1PromptsPromptIdSnapshotRoute: ApiV1PromptsPromptIdSnapshotRoute,
}

const ApiV1PromptsPromptIdRouteWithChildren =
  ApiV1PromptsPromptIdRoute._addFileChildren(ApiV1PromptsPromptIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiManifestIndexRoute: ApiManifestIndexRoute,
  ApiOgIndexRoute: ApiOgIndexRoute,
  ApiSetupStatusIndexRoute: ApiSetupStatusIndexRoute,
  ApiV1BrandsBrandIdRoute: ApiV1BrandsBrandIdRoute,
  ApiV1CompetitorsCompetitorIdRoute: ApiV1CompetitorsCompetitorIdRoute,
  ApiV1PromptsPromptIdRoute: ApiV1PromptsPromptIdRouteWithChildren,
  ApiV1ReportsReportIdRoute: ApiV1ReportsReportIdRoute,
  ApiV1ToolsAnalyzeRoute: ApiV1ToolsAnalyzeRoute,
  ApiPlausibleEventIndexRoute: ApiPlausibleEventIndexRoute,
  ApiV1BrandsIndexRoute: ApiV1BrandsIndexRoute,
  ApiV1CompetitorsIndexRoute: ApiV1CompetitorsIndexRoute,
  ApiV1DocsIndexRoute: ApiV1DocsIndexRoute,
  ApiV1PromptsIndexRoute: ApiV1PromptsIndexRoute,
  ApiV1ReportsIndexRoute: ApiV1ReportsIndexRoute,
  ApiPlausibleJsScriptIndexRoute: ApiPlausibleJsScriptIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
