# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from ...types.report_prompt_snapshot import ReportPromptSnapshot
from .get_report_response_status import GetReportResponseStatus
from .get_report_response_unstable import GetReportResponseUnstable


class GetReportResponse(UniversalBaseModel):
    report_id: typing_extensions.Annotated[str, FieldMetadata(alias="reportId"), pydantic.Field(alias="reportId")]
    status: GetReportResponseStatus
    progress: typing.Optional[int] = pydantic.Field(default=None)
    """
    Generation progress percentage (0-100). Available while processing.
    """

    brand_name: typing_extensions.Annotated[str, FieldMetadata(alias="brandName"), pydantic.Field(alias="brandName")]
    brand_aliases: typing_extensions.Annotated[
        typing.List[str], FieldMetadata(alias="brandAliases"), pydantic.Field(alias="brandAliases")
    ]
    brand_website: typing_extensions.Annotated[
        str, FieldMetadata(alias="brandWebsite"), pydantic.Field(alias="brandWebsite")
    ]
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ]
    completed_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="completedAt"), pydantic.Field(alias="completedAt")
    ] = None
    prompts: typing.Optional[typing.List[ReportPromptSnapshot]] = pydantic.Field(default=None)
    """
    Per-prompt snapshot data. Only present when status is 'completed'.
    """

    unstable: typing.Optional[GetReportResponseUnstable] = pydantic.Field(default=None)
    """
    Derived stats (SoV, visibility, etc.). Format may change between versions. Only present when status is 'completed'.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
