// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         promptId: "promptId",
 *         runId: "runId"
 *     }
 */
export interface GetRunRequest {
    promptId: string;
    runId: string;
}
