// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         promptId: "promptId",
 *         start: "2024-01-15T09:30:00Z",
 *         end: "2024-01-15T09:30:00Z"
 *     }
 */
export interface ListPromptRunsRequest {
    promptId: string;
    /** Inclusive lower bound of the window, an ISO 8601 timestamp such as `2026-01-01T00:00:00Z`. A bare `YYYY-MM-DD` is rejected: that is `/prompts/{promptId}/snapshot`'s spelling and means a local calendar day there. */
    start: string;
    /** Exclusive upper bound of the window, an ISO 8601 timestamp. The window is half-open: a run at exactly `end` is outside it. */
    end: string;
    /** Restrict to one model, e.g. `chatgpt`. See `GET /models`. */
    model?: string;
    /** Page number, 1-based. */
    page?: number;
    /** Items per page. Values above the maximum are clamped, not rejected. */
    limit?: number;
}
