// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         promptId: "promptId"
 *     }
 */
export interface DeletePromptRequest {
    /** The ID of the prompt to delete */
    promptId: string;
}
