// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         brandName: "brandName",
 *         brandWebsite: "brandWebsite"
 *     }
 */
export interface CreateReportRequest {
    /** The brand name to analyze */
    brandName: string;
    /** Other names the brand goes by (spellings, abbreviations, product names). A mention of any of them counts as a brand mention. */
    brandAliases?: string[];
    /** The brand's website — a domain (nike.com) or a full URL. A URL with a path (e.g. https://www.nike.com/golf) scopes the analysis to that page; mentions are tracked against its domain either way. */
    brandWebsite: string;
    /** Optional list of custom prompts to include in the report */
    manualPrompts?: string[];
}
