// This file was auto-generated by Fern from our API Definition.

export interface ApiKeyIdentity {
    /** `admin` for an instance key, `organization` for a dashboard-issued key. */
    keyType: ApiKeyIdentity.KeyType;
    /** The organization this key acts inside. Null for admin keys. */
    organizationId: string | null;
    organizationName: string | null;
    /** Scopes this key holds. A read-write key lists both; an admin key always does. */
    scopes: ApiKeyIdentity.Scopes.Item[];
    /** Brands the key is narrowed to, or null when it reaches every brand in its organization. Never an empty array — a restriction to no brands is rejected at creation rather than treated as no restriction. */
    brandIds: string[] | null;
    createdAt: string | null;
    /** When the key stops working, if it has an expiry. */
    expiresAt: string | null;
    /** The key's configured limit — generous by design: it exists to stop a runaway loop, not to meter normal use. Enforcement is a fixed window and approximate under concurrency. */
    rateLimit: ApiKeyIdentity.RateLimit | null;
    /** The key's label, as given when it was issued. Null for admin keys. */
    createdBy: string | null;
    lastUsedAt: string | null;
}

export namespace ApiKeyIdentity {
    /** `admin` for an instance key, `organization` for a dashboard-issued key. */
    export const KeyType = {
        Admin: "admin",
        Organization: "organization",
    } as const;
    export type KeyType = (typeof KeyType)[keyof typeof KeyType];
    export type Scopes = Scopes.Item[];

    export namespace Scopes {
        export const Item = {
            Read: "read",
            Write: "write",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }

    /**
     * The key's configured limit — generous by design: it exists to stop a runaway loop, not to meter normal use. Enforcement is a fixed window and approximate under concurrency.
     */
    export interface RateLimit {
        limit: number;
        window: RateLimit.Window;
    }

    export namespace RateLimit {
        export const Window = {
            Minute: "minute",
            Hour: "hour",
        } as const;
        export type Window = (typeof Window)[keyof typeof Window];
    }
}
