// This file was auto-generated by Fern from our API Definition.

import type * as Elmo from "../index.js";

/**
 * Every non-paginated figure for a brand over one window. There is no parameter for selecting a subset: the four computations behind this share one scope resolution and run concurrently, so a subset would save a caller a fraction of one request and cost everyone a parameter to reason about.
 */
export interface BrandAnalytics {
    brandId: string;
    brandName: string;
    range: Elmo.DateRange;
    /** How often the brand is mentioned at all. */
    visibility: BrandAnalytics.Visibility;
    /** The brand against its tracked competitors. */
    shareOfVoice: BrandAnalytics.ShareOfVoice;
    /** Per-model visibility and run counts. Only models that produced a run in the window appear. */
    models: Elmo.ModelVisibility[];
    totals: BrandAnalytics.Totals;
}

export namespace BrandAnalytics {
    /**
     * How often the brand is mentioned at all.
     */
    export interface Visibility {
        /** The last plotted point — the number the dashboard hero shows. Ratio 0–1; multiply by 100 for a percentage. */
        current: number | null;
        series: Elmo.VisibilityPoint[];
    }

    /**
     * The brand against its tracked competitors.
     */
    export interface ShareOfVoice {
        /** The brand's own share at the end of the window. Ratio 0–1; multiply by 100 for a percentage. */
        brand: number | null;
        /** Leaderboard, highest share first. */
        entries: Elmo.ShareOfVoiceEntry[];
        /** The brand's share over time. */
        series: Elmo.ShareOfVoicePoint[];
    }

    export interface Totals {
        runs: number;
        /** Enabled prompts counted in the window. */
        prompts: number;
        citations: number;
        uniqueDomains: number;
        uniqueUrls: number;
    }
}
