// This file was auto-generated by Fern from our API Definition.

import type * as Elmo from "../index.js";

/**
 * The brand's latest Opportunities report — the same LLM-generated analysis the dashboard shows, read from the append-only history rather than regenerated. Elmo decides when to produce a new one; there is no way to trigger generation over the API, because it spends provider budget with no per-call metering behind it.
 */
export interface BrandOpportunities {
    brandId: string;
    /** `ready` when a report is present. `insufficient-data` when the brand hasn't accumulated enough tracked answers to say anything useful yet, in which case the lists are empty. */
    status: BrandOpportunities.Status;
    generatedAt: string | null;
    /** The model that produced the report, when recorded. */
    model: string | null;
    /** A few bullets on where the brand stands and the through-line of the plan. */
    summary: string[];
    /** Prioritized, highest impact first. */
    opportunities: Elmo.Opportunity[];
    /** Caveats: hard-to-win areas, or tactics to avoid. */
    risks: string[];
}

export namespace BrandOpportunities {
    /** `ready` when a report is present. `insufficient-data` when the brand hasn't accumulated enough tracked answers to say anything useful yet, in which case the lists are empty. */
    export const Status = {
        Ready: "ready",
        InsufficientData: "insufficient-data",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
