// This file was auto-generated by Fern from our API Definition.

export interface Brand {
    /** User-supplied brand identifier (e.g. "acme") */
    id: string;
    name: string;
    /** Brand domains. The first entry is the primary website; remaining entries are additional domains. */
    domains: string[];
    aliases: string[];
    enabled: boolean;
    onboarded: boolean;
    createdAt: string;
    updatedAt: string;
    /** The organization that owns this brand and is billed for it. */
    organizationId: string;
    /** Models this brand is tracked on. Null means the deployment default. */
    enabledModels: string[] | null;
    /** Sampling cadence override in hours. Null means the plan cadence. */
    delayOverrideHours: number | null;
}
