// This file was auto-generated by Fern from our API Definition.

export interface CitationUrl {
    url: string;
    domain: string;
    title: string | null;
    /** Which side of the citation landscape the domain sits on. */
    category: CitationUrl.Category;
    /** What kind of page was cited. */
    pageType: CitationUrl.PageType;
    count: number;
    promptCount: number;
    /** Not cited in the equal-length window immediately before this one. */
    isNew: boolean;
}

export namespace CitationUrl {
    /** Which side of the citation landscape the domain sits on. */
    export const Category = {
        Brand: "brand",
        Competitor: "competitor",
        Editorial: "editorial",
        Reviews: "reviews",
        Ecommerce: "ecommerce",
        Social: "social",
        Developer: "developer",
        Pr: "pr",
        Reference: "reference",
        Institutional: "institutional",
        Other: "other",
    } as const;
    export type Category = (typeof Category)[keyof typeof Category];
    /** What kind of page was cited. */
    export const PageType = {
        Homepage: "homepage",
        Article: "article",
        Listicle: "listicle",
        Howto: "howto",
        Comparison: "comparison",
        Review: "review",
        Forum: "forum",
        Video: "video",
        Doc: "doc",
        Product: "product",
        Info: "info",
        Search: "search",
        Shopping: "shopping",
        Other: "other",
    } as const;
    export type PageType = (typeof PageType)[keyof typeof PageType];
}
