// This file was auto-generated by Fern from our API Definition.

export interface CitedUrlEntry {
    /** The cited URL */
    url: string;
    /** Page title if available */
    title: string | null;
    /** Number of times this URL was cited */
    count: number;
}
