// This file was auto-generated by Fern from our API Definition.

export interface OpportunityPrompt {
    /** The prompt as the report names it. */
    text: string;
    /** The tracked prompt it resolved to, or null when it didn't match one. */
    promptId: string | null;
}
