// This file was auto-generated by Fern from our API Definition.

export interface Pagination {
    page: number;
    limit: number;
    /** Total items matching the request. */
    total: number;
    totalPages: number;
}
