// This file was auto-generated by Fern from our API Definition.

import type * as Elmo from "../index.js";

/**
 * Per-prompt snapshot of raw mention data from a report. Consumers compute SoV and other derived metrics.
 */
export interface ReportPromptSnapshot {
    /** The prompt text that was evaluated */
    promptValue: string;
    /** Number of evaluation runs for this prompt */
    totalRuns: number;
    mentions: Elmo.MentionsSummary;
}
