// This file was auto-generated by Fern from our API Definition.

import type * as Elmo from "../index.js";

export interface RunList {
    data: Elmo.RunSummary[];
    pagination: Elmo.Pagination;
}
