// This file was auto-generated by Fern from our API Definition.

/**
 * A single model answer, without its text. Fetch `GET /prompts/{promptId}/runs/{runId}` for the answer itself.
 */
export interface RunSummary {
    id: string;
    promptId: string;
    brandId: string;
    model: string;
    /** How the answer was obtained. Informational; not a stable enum. */
    provider: string | null;
    /** Whether the engine answered with its own web search on. */
    webSearchEnabled: boolean;
    brandMentioned: boolean;
    competitorsMentioned: string[];
    /** Searches the engine ran, where it exposes them. */
    webQueries: string[];
    citationCount: number;
    createdAt: string;
}
