// This file was auto-generated by Fern from our API Definition.

export interface VisibilityPoint {
    date: string;
    /** Null on days with no runs to plot; the series is not gap-filled with zeros. Ratio 0–1; multiply by 100 for a percentage. */
    visibility: number | null;
}
