import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { getAppConfig } from "@/lib/adapters";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { providers } = getAppConfig();
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <providers.auth.Provider>
          {children}
        </providers.auth.Provider>
      </body>
    </html>
  );
}
