import type { Competitor } from "./types";

// Sorted by descending Ahrefs Domain Rating
export const competitors: Competitor[] = [
	{
		slug: "hubspot-aeo-grader",
		name: "HubSpot AEO Grader",
		domain: "hubspot.com",
		url: "https://www.hubspot.com/products/marketing/aeo-grader",
		tagline: "Free AI search grader from HubSpot's marketing suite",
		description:
			"HubSpot's AEO Grader is a free tool that analyzes how well your website is optimized for AI search engines. It checks content structure, schema markup, and AI readability to provide actionable recommendations. As part of HubSpot's broader marketing platform, it benefits from deep integration with their CRM and content tools.",
		category: "seo-traditional",
		ahrefsDR: 93,
		status: "active",
		features: {
			visibilityScore: true,
			brandMentionTracking: true,
			actionRecommendations: true,
			siteAudits: true,
		},
		pricing: { hasFree: true, hasEnterprise: true },
		highlights: [
			"Free standalone audit tool",
			"Part of HubSpot's marketing ecosystem",
			"Content optimization recommendations",
		],
	},
	{
		slug: "semrush-ai-toolkit",
		name: "Semrush AI Toolkit",
		domain: "semrush.com",
		url: "https://www.semrush.com/ai-seo/brand-performance/",
		tagline: "Established SEO platform expanding into AI visibility tracking",
		description:
			"Semrush's AI SEO toolkit adds AI visibility tracking to their established SEO platform. Their Brand Performance tool monitors how AI search engines mention and recommend your brand, with integration into their keyword database and competitive intelligence tools.",
		category: "seo-traditional",
		ahrefsDR: 92,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			competitorBenchmarking: true,
			brandMentionTracking: true,
			promptVolumeEstimates: true,
			sentimentAnalysis: true,
			geographicTracking: true,
			socialMediaTracking: true,
			multiLanguage: true,
			actionRecommendations: true,
			contentGapAnalysis: true,
			siteAudits: true,
			keywordResearch: true,
			emailAlerts: true,
			dataExportApi: true,
			biConnectors: true,
			whiteLabelAgency: true,
			contentGeneration: true,
		},
		pricing: { hasFree: false, startingPrice: "$139.95/mo", hasEnterprise: true },
		highlights: [
			"Integrated with Semrush's SEO data platform",
			"Traditional SEO + AI tracking unified",
			"Enterprise-grade reporting and API",
		],
	},
	{
		slug: "ahrefs-brand-radar",
		name: "Ahrefs Brand Radar",
		domain: "ahrefs.com",
		url: "https://ahrefs.com/brand-radar",
		tagline: "Ahrefs' AI brand monitoring tool",
		description:
			"Ahrefs Brand Radar adds AI visibility tracking to their established SEO platform. It monitors how AI chatbots mention your brand, tracks sentiment, and identifies citation sources. Integrates with Ahrefs' backlink and keyword database for competitive analysis.",
		category: "seo-traditional",
		ahrefsDR: 91,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			competitorBenchmarking: true,
			brandMentionTracking: true,
			promptVolumeEstimates: true,
			sentimentAnalysis: true,
			socialMediaTracking: true,
			multiLanguage: true,
			contentGapAnalysis: true,
			keywordResearch: true,
			emailAlerts: true,
			dataExportApi: true,
		},
		pricing: { hasFree: false, startingPrice: "$129/mo", hasEnterprise: true },
		highlights: [
			"Integrates with Ahrefs' backlink data",
			"Reddit and social media brand monitoring",
			"Integrates with existing Ahrefs workflows",
		],
	},
	{
		slug: "amplitude",
		name: "Amplitude",
		domain: "amplitude.com",
		url: "https://amplitude.com",
		tagline: "Product analytics platform adding AI search features",
		description:
			"Amplitude, a product analytics platform, has announced AEO features that extend their analytics capabilities into AI search visibility. Their background in behavioral analytics informs their approach to understanding how AI platforms surface brands and products.",
		category: "tracking",
		ahrefsDR: 86,
		status: "active",
		features: {
			brandMentionTracking: true,
			crawlerAnalytics: true,
			emailAlerts: true,
			dataExportApi: true,
			biConnectors: true,
		},
		pricing: { hasFree: true, hasEnterprise: true },
		highlights: [
			"Enterprise analytics platform",
			"Behavioral analytics background",
			"BI and data pipeline integrations",
		],
		notes: "AEO features announced via CEO Spencer Skates on X",
	},
	{
		slug: "se-ranking",
		name: "SE Ranking",
		domain: "seranking.com",
		url: "https://seranking.com/ai-overviews-tracker.html",
		tagline: "All-in-one SEO platform with AI Overviews and ChatGPT tracking",
		description:
			"SE Ranking adds AI visibility tracking to their comprehensive SEO toolkit, offering both an AI Overviews Tracker and a ChatGPT Visibility Tracker. Monitors how your brand appears in Google's AI-generated results and ChatGPT responses, with integration into their keyword tracking and competitive analysis tools.",
		category: "seo-traditional",
		ahrefsDR: 84,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			competitorBenchmarking: true,
			brandMentionTracking: true,
			geographicTracking: true,
			keywordResearch: true,
			emailAlerts: true,
			dataExportApi: true,
			whiteLabelAgency: true,
		},
		pricing: { hasFree: false, startingPrice: "$65/mo", hasEnterprise: true },
		highlights: [
			"AI Overviews + ChatGPT tracking in one platform",
			"Integrated with comprehensive SEO toolkit",
			"White-label available for agencies",
		],
	},
	{
		slug: "writesonic",
		name: "Writesonic",
		domain: "writesonic.com",
		url: "https://writesonic.com/",
		tagline: "AI content engine with 120M+ conversation dataset for AEO",
		description:
			"Writesonic combines AI content generation with AI search optimization, powered by a proprietary dataset of over 120 million AI conversations. Their platform tracks visibility across AI platforms and uses their conversation data to provide prompt volume estimates and content recommendations.",
		category: "content",
		ahrefsDR: 84,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			competitorBenchmarking: true,
			brandMentionTracking: true,
			promptVolumeEstimates: true,
			actionRecommendations: true,
			keywordResearch: true,
			dataExportApi: true,
			contentGeneration: true,
		},
		pricing: { hasFree: true, startingPrice: "$49/mo", hasEnterprise: true },
		highlights: [
			"120M+ AI conversation dataset for prompt volumes",
			"Combined tracking + content generation platform",
			"Precise action plans based on AI data",
		],
	},
	{
		slug: "frase",
		name: "Frase",
		domain: "frase.io",
		url: "https://www.frase.io/",
		tagline: "Agentic SEO and GEO platform with 80+ AI tools",
		description:
			"Frase has evolved from a content optimization platform into an Agentic SEO and GEO platform with over 80 AI-powered tools. Their approach includes content atomization, programmatic SEO from data, and AI crawler analytics. Covers both content creation and AI visibility tracking.",
		category: "content",
		ahrefsDR: 79,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			brandMentionTracking: true,
			crawlerAnalytics: true,
			keywordResearch: true,
			contentGapAnalysis: true,
			dataExportApi: true,
			contentGeneration: true,
		},
		pricing: { hasFree: false, startingPrice: "$15/mo", hasEnterprise: true },
		highlights: [
			"80+ AI-powered SEO and GEO tools",
			"Content atomization and programmatic SEO",
			"Agentic AI workflows for content creation",
		],
	},
	{
		slug: "babylovegrowth",
		name: "BabyLoveGrowth",
		domain: "babylovegrowth.ai",
		url: "https://www.babylovegrowth.ai/",
		tagline: "Autopilot AI content, backlinks, and Reddit agent",
		description:
			"BabyLoveGrowth offers a fully automated approach to AI visibility, combining content creation, backlink exchange through a network of 2,500+ partner sites, and a Reddit engagement agent. Positioned as an all-in-one autopilot for increasing AI citations through content distribution and link building.",
		category: "content",
		ahrefsDR: 76,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			brandMentionTracking: true,
			socialMediaTracking: true,
			contentGeneration: true,
		},
		pricing: { hasFree: false, hasEnterprise: false },
		highlights: [
			"2,500+ partner site backlink network",
			"Automated Reddit engagement agent",
			"Full autopilot content + links approach",
		],
	},
	{
		slug: "profound",
		name: "Profound",
		domain: "tryprofound.com",
		url: "https://www.tryprofound.com/",
		tagline: "G2 AEO Leader with prompt volumes and Agent Analytics",
		description:
			"Profound was named the G2 AEO Leader in the inaugural G2 Grid report. They offer prompt volume estimates, Agent Analytics for tracking AI crawler behavior, and count enterprise customers including MongoDB, Figma, Zapier, and Ramp among their users. Featured in Fortune, WSJ, NYT, TechCrunch, and Financial Times.",
		category: "tracking",
		ahrefsDR: 75,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			competitorBenchmarking: true,
			brandMentionTracking: true,
			promptVolumeEstimates: true,
			crawlerAnalytics: true,
			shoppingTracking: true,
			actionRecommendations: true,
			emailAlerts: true,
			dataExportApi: true,
			contentGeneration: true,
		},
		pricing: { hasFree: false, hasEnterprise: true },
		highlights: [
			"G2 AEO Leader",
			"Agent Analytics for AI crawler tracking",
			"Enterprise: MongoDB, Figma, Zapier, Ramp, US Bank",
			"Featured in Fortune, WSJ, NYT, TechCrunch",
		],
	},
	{
		slug: "dataforseo",
		name: "DataForSEO AEO",
		domain: "dataforseo.com",
		url: "https://dataforseo.com/",
		tagline: "SEO data API provider with AI search tracking endpoints",
		description:
			"DataForSEO is an SEO data API provider that offers AI search tracking capabilities through their API. Their AEO offering provides programmatic access to AI search results, visibility metrics, and citation data. Built for developers and platforms that need to integrate AI visibility data into their own products.",
		category: "api-developer",
		ahrefsDR: 74,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			geographicTracking: true,
			multiLanguage: true,
			dataExportApi: true,
		},
		pricing: { hasFree: false, hasEnterprise: true },
		highlights: [
			"API-first approach for developers and platforms",
			"SEO data infrastructure",
			"Used by many AEO tools as a data source",
		],
	},
	{
		slug: "rankability",
		name: "Rankability",
		domain: "rankability.com",
		url: "https://www.rankability.com/",
		tagline: "AI Search Analyzer with NLP and entity focus",
		description:
			"Rankability combines traditional SEO expertise with AI search analysis, using NLP and entity extraction to understand how AI platforms interpret and recommend content. Their AI Search Analyzer evaluates content against AI ranking factors and provides optimization recommendations. Primarily agency-focused.",
		category: "content",
		ahrefsDR: 73,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			brandMentionTracking: true,
			siteAudits: true,
			keywordResearch: true,
			contentGeneration: true,
			whiteLabelAgency: true,
		},
		pricing: { hasFree: false, hasEnterprise: true },
		highlights: [
			"NLP and entity-focused analysis",
			"AI Search Analyzer tool",
			"Agency-focused with white-label options",
		],
	},
	{
		slug: "airops",
		name: "AirOps",
		domain: "airops.com",
		url: "https://www.airops.com/",
		tagline: "Content Engineering platform with AI workflows and Page360",
		description:
			"AirOps is a Content Engineering platform that helps enterprises create AI-optimized content at scale. Their Page360 feature analyzes content performance in AI search, while their workflow automation handles content refresh, creation, and optimization. Focused on enterprise content operations with brand kits and team collaboration.",
		category: "content",
		ahrefsDR: 73,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			brandMentionTracking: true,
			contentGapAnalysis: true,
			dataExportApi: true,
			contentGeneration: true,
		},
		pricing: { hasFree: true, hasEnterprise: true },
		highlights: [
			"Page360 content performance analysis",
			"Enterprise content engineering workflows",
			"Brand kits and collaboration tools",
		],
	},
	{
		slug: "peec-ai",
		name: "Peec AI",
		domain: "peec.ai",
		url: "https://peec.ai/",
		tagline: "$29M-funded AI visibility platform with Looker Studio integration",
		description:
			"Peec AI raised $29M in Series A funding. Based in Berlin, they offer prompt volume estimates, sentiment analysis, Looker Studio connectors, and AI visibility tracking across multiple LLMs.",
		category: "tracking",
		ahrefsDR: 71,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			competitorBenchmarking: true,
			brandMentionTracking: true,
			promptVolumeEstimates: true,
			sentimentAnalysis: true,
			actionRecommendations: true,
			contentGapAnalysis: true,
			emailAlerts: true,
			dataExportApi: true,
			biConnectors: true,
		},
		pricing: { hasFree: false, hasEnterprise: true },
		highlights: [
			"$29M Series A funding",
			"Looker Studio native connector",
			"Prompt volume estimates with sentiment tracking",
		],
	},
	{
		slug: "nightwatch",
		name: "Nightwatch",
		domain: "nightwatch.io",
		url: "https://nightwatch.io/ai-tracking/",
		tagline: "Traditional SEO rank tracker with 190K locations + AI tracking",
		description:
			"Nightwatch is an established SEO rank tracking platform that has added AI visibility tracking to their toolkit. With 190,000 tracking locations worldwide, they offer unified traditional SEO + AI search monitoring. Their Prompt Research feature helps discover relevant AI search queries.",
		category: "seo-traditional",
		ahrefsDR: 71,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			competitorBenchmarking: true,
			brandMentionTracking: true,
			geographicTracking: true,
			keywordResearch: true,
			emailAlerts: true,
			dataExportApi: true,
			biConnectors: true,
			whiteLabelAgency: true,
		},
		pricing: { hasFree: false, startingPrice: "$39/mo", hasEnterprise: true },
		highlights: [
			"190,000 tracking locations worldwide",
			"Unified traditional SEO + AI tracking",
			"Prompt Research feature for AI query discovery",
		],
	},
	{
		slug: "local-falcon",
		name: "Local Falcon",
		domain: "localfalcon.com",
		url: "https://www.localfalcon.com/",
		tagline: "First local SEO platform with AI visibility (SAIV metric)",
		description:
			"Local Falcon was an early entrant in local SEO + AI visibility tracking, introducing the SAIV (Share of AI Visibility) metric. They combine geo-grid rank tracking for local search with AI visibility monitoring, targeting local businesses and multi-location brands. Available for purchase on Microns.",
		category: "tracking",
		ahrefsDR: 71,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			competitorBenchmarking: true,
			brandMentionTracking: true,
			geographicTracking: true,
			dataExportApi: true,
			biConnectors: true,
			whiteLabelAgency: true,
		},
		pricing: { hasFree: false, startingPrice: "$24/mo", hasEnterprise: true },
		highlights: [
			"Early entrant in local SEO + AI visibility",
			"SAIV (Share of AI Visibility) metric",
			"Looker Studio integration for agencies",
		],
		notes: "Possibly for sale on Microns marketplace",
	},
	{
		slug: "otterly-ai",
		name: "OtterlyAI",
		domain: "otterly.ai",
		url: "https://otterly.ai/",
		tagline: "Gartner Cool Vendor 2025 with GEO Audit (25+ factors)",
		description:
			"OtterlyAI was named a Gartner Cool Vendor 2025 and reports over 20,000 users. Their GEO Audit evaluates 25+ on-page factors for AI readability. They also offer AI keyword research, crawler simulation, and industry benchmarks.",
		category: "tracking",
		ahrefsDR: 70,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			competitorBenchmarking: true,
			brandMentionTracking: true,
			crawlerAnalytics: true,
			geographicTracking: true,
			actionRecommendations: true,
			siteAudits: true,
			keywordResearch: true,
			emailAlerts: true,
			whiteLabelAgency: true,
		},
		pricing: { hasFree: false, hasEnterprise: true },
		highlights: [
			"Gartner Cool Vendor 2025",
			"20,000+ users",
			"GEO Audit evaluating 25+ on-page factors",
		],
	},
	{
		slug: "scrunch",
		name: "Scrunch",
		domain: "scrunch.com",
		url: "https://scrunch.com/",
		tagline: "Agent Experience Platform (AXP) for AI content optimization",
		description:
			"Scrunch positions itself as an Agent Experience Platform (AXP), reformatting and optimizing content specifically for AI consumption. Their approach focuses on making content easily digestible by AI crawlers and language models, with site audit capabilities and AI-ready content recommendations.",
		category: "content",
		ahrefsDR: 70,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			brandMentionTracking: true,
			crawlerAnalytics: true,
			actionRecommendations: true,
			siteAudits: true,
			contentGeneration: true,
		},
		pricing: { hasFree: false, hasEnterprise: true },
		highlights: [
			"AXP (Agent Experience Platform) concept",
			"Reformats content for AI consumption",
			"AI crawler analytics and site audits",
		],
	},
	{
		slug: "athenahq",
		name: "AthenaHQ",
		domain: "athenahq.ai",
		url: "https://www.athenahq.ai/",
		tagline: "Action-focused AI blindspot detection with content workflows",
		description:
			"AthenaHQ focuses on detecting AI blindspots and turning visibility data into content workflows. Their conversation explorer lets you browse AI responses, while their persona-based auto-tagging and action recommendations help teams prioritize content creation.",
		category: "tracking",
		ahrefsDR: 58,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			competitorBenchmarking: true,
			brandMentionTracking: true,
			sentimentAnalysis: true,
			actionRecommendations: true,
			contentGapAnalysis: true,
			siteAudits: true,
			contentGeneration: true,
		},
		pricing: { hasFree: false, hasEnterprise: true },
		highlights: [
			"AI blindspot detection methodology",
			"Persona-based auto-tagging",
			"Action-focused content workflows",
		],
	},
	{
		slug: "promptwatch",
		name: "Promptwatch",
		domain: "promptwatch.com",
		url: "https://promptwatch.com/",
		tagline: "Real UI scraping with 630M+ citations tracked",
		description:
			"Promptwatch scrapes actual AI user interfaces rather than using APIs, which they say provides \"real user experience\" data. They report tracking over 630 million citations and 5,700+ brands. Featured in WSJ and Axios, they offer tracking including shopping and geographic features.",
		category: "tracking",
		ahrefsDR: 56,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			competitorBenchmarking: true,
			brandMentionTracking: true,
			promptVolumeEstimates: true,
			sentimentAnalysis: true,
			crawlerAnalytics: true,
			geographicTracking: true,
			socialMediaTracking: true,
			shoppingTracking: true,
			emailAlerts: true,
			dataExportApi: true,
		},
		pricing: { hasFree: false, hasEnterprise: true },
		highlights: [
			"UI scraping vs API — claims more accurate data",
			"630M+ citations tracked, 5,700+ brands",
			"Featured in WSJ and Axios",
		],
	},
	{
		slug: "llmrefs",
		name: "LLMrefs",
		domain: "llmrefs.com",
		url: "https://llmrefs.com/",
		tagline: "Keyword-based tracking with auto fan-out prompts",
		description:
			"LLMrefs takes a keyword-first approach to AI visibility tracking, automatically generating relevant prompts from your keywords (fan-out). This makes it more familiar for SEO professionals transitioning to AEO. Lists eBay, HubSpot, and NVIDIA among its users.",
		category: "tracking",
		ahrefsDR: 55,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			competitorBenchmarking: true,
			brandMentionTracking: true,
			promptVolumeEstimates: true,
			socialMediaTracking: true,
			contentGapAnalysis: true,
			siteAudits: true,
			dataExportApi: true,
			biConnectors: true,
		},
		pricing: { hasFree: false, startingPrice: "$79/mo", hasEnterprise: true },
		highlights: [
			"Keyword-based tracking — familiar for SEO pros",
			"Auto fan-out prompt generation from keywords",
			"Trusted by eBay, HubSpot, NVIDIA",
		],
	},
	{
		slug: "geneo",
		name: "Geneo",
		domain: "geneo.app",
		url: "https://geneo.app/",
		tagline: "AI visibility platform with optimization recommendations",
		description:
			"Geneo provides AI visibility tracking with a focus on actionable optimization recommendations. Their platform monitors how AI search engines surface your brand and provides concrete steps to improve visibility. Includes content optimization features to help implement recommendations.",
		category: "tracking",
		ahrefsDR: 54,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			brandMentionTracking: true,
			actionRecommendations: true,
			contentGeneration: true,
		},
		pricing: { hasFree: false, hasEnterprise: false },
		highlights: [
			"Optimization recommendations with each insight",
			"Content-focused improvement suggestions",
		],
	},
	{
		slug: "gushwork",
		name: "Gushwork",
		domain: "gushwork.ai",
		url: "https://www.gushwork.ai/",
		tagline: "AI-powered SEO platform ($9M raised)",
		description:
			"Gushwork raised $9M and offers an AI-powered SEO platform with a slightly different positioning than pure AEO tools. Their approach combines AI content creation with search optimization, using AI agents to handle SEO workflows end-to-end.",
		category: "content",
		ahrefsDR: 54,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			brandMentionTracking: true,
			keywordResearch: true,
			contentGeneration: true,
		},
		pricing: { hasFree: false, hasEnterprise: true },
		highlights: [
			"$9M raised in funding",
			"AI agents for end-to-end SEO workflows",
		],
	},
	{
		slug: "goodie",
		name: "Goodie",
		domain: "higoodie.com",
		url: "https://higoodie.com/",
		tagline: "AI visibility tracking with Amazon Rufus tracking and training course",
		description:
			"Goodie (HiGoodie) offers AI visibility tracking with a focus on Amazon Rufus tracking for e-commerce brands. They also offer educational courses on AEO methodology.",
		category: "tracking",
		ahrefsDR: 51,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			competitorBenchmarking: true,
			brandMentionTracking: true,
			shoppingTracking: true,
		},
		pricing: { hasFree: false, hasEnterprise: false },
		highlights: [
			"Educational courses on AEO methodology",
			"Amazon Rufus shopping tracking",
			"Thought leadership content",
		],
	},
	{
		slug: "aeo-engine",
		name: "AEO Engine",
		domain: "aeoengine.ai",
		url: "https://aeoengine.ai/",
		tagline: "E-commerce focused AEO platform with schema optimization",
		description:
			"AEO Engine focuses on AI search optimization specifically for e-commerce businesses. Their platform helps online retailers optimize product pages, implement JSON-LD schema, and track visibility in AI shopping features. Tailored for Shopify and WooCommerce stores.",
		category: "ecommerce",
		ahrefsDR: 50,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			brandMentionTracking: true,
			shoppingTracking: true,
			siteAudits: true,
		},
		pricing: { hasFree: false, hasEnterprise: false },
		highlights: [
			"E-commerce focused AEO",
			"JSON-LD schema optimization",
			"Shopify and WooCommerce support",
		],
	},
	{
		slug: "rebel-growth",
		name: "Rebel Growth",
		domain: "rebelgrowth.com",
		url: "https://rebelgrowth.com/",
		tagline: "Growth-focused AEO agency and tooling",
		description:
			"Rebel Growth offers AEO tracking and consulting services, combining tooling with strategic guidance. Their approach focuses on growth outcomes rather than just visibility metrics, helping brands understand and improve their presence in AI search results.",
		category: "tracking",
		ahrefsDR: 50,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			brandMentionTracking: true,
			actionRecommendations: true,
		},
		pricing: { hasFree: false, hasEnterprise: false },
		highlights: [
			"Growth-focused approach to AEO",
			"Consulting + tooling combined",
		],
	},
	{
		slug: "knowatoa",
		name: "Knowatoa",
		domain: "knowatoa.com",
		url: "https://knowatoa.com/",
		tagline: "BISCUIT Framework methodology with multi-language tracking",
		description:
			"Knowatoa offers AI visibility tracking built around their proprietary BISCUIT Framework methodology for understanding AI rankings. They provide multi-language and multi-location tracking, sentiment analysis, and Looker Studio / NinjaCat integrations.",
		category: "tracking",
		ahrefsDR: 48,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			competitorBenchmarking: true,
			brandMentionTracking: true,
			sentimentAnalysis: true,
			geographicTracking: true,
			multiLanguage: true,
			biConnectors: true,
		},
		pricing: { hasFree: false, startingPrice: "$59/mo", hasEnterprise: true },
		highlights: [
			"Proprietary BISCUIT Framework methodology",
			"Multi-language and multi-location tracking",
			"Looker Studio and NinjaCat integrations",
		],
	},
	{
		slug: "aiseotracker",
		name: "AISEOTracker",
		domain: "aiseotracker.com",
		url: "https://aiseotracker.com/",
		tagline: "249K+ brands tracked with Page Inspector feature",
		description:
			"AISEOTracker reports monitoring over 249,000 brands. Their Page Inspector shows how AI crawlers see your content (stripped HTML view), helping identify invisible content like dynamic pricing or JS-heavy elements. Offers a free visibility report.",
		category: "tracking",
		ahrefsDR: 48,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			competitorBenchmarking: true,
			brandMentionTracking: true,
			siteAudits: true,
		},
		pricing: { hasFree: true, hasEnterprise: false },
		highlights: [
			"249,000+ brands tracked",
			"Page Inspector — see how AI crawlers view your content",
			"Free visibility report available",
		],
	},
	{
		slug: "promptmonitor",
		name: "Promptmonitor",
		domain: "promptmonitor.io",
		url: "https://www.promptmonitor.io/",
		tagline: "200+ countries with AI bot analytics and privacy-first approach",
		description:
			"Promptmonitor offers geographic tracking across 200+ countries, AI bot analytics, and bundled privacy-first web analytics. Their platform monitors AI visibility while also tracking when AI crawlers visit your site. Sold for $85,000 in a notable acquisition. Known for their privacy-first analytics bundle.",
		category: "tracking",
		ahrefsDR: 47,
		status: "acquired",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			competitorBenchmarking: true,
			brandMentionTracking: true,
			sentimentAnalysis: true,
			crawlerAnalytics: true,
			geographicTracking: true,
			emailAlerts: true,
			dataExportApi: true,
			whiteLabelAgency: true,
		},
		pricing: { hasFree: false, startingPrice: "$29/mo", hasEnterprise: true },
		highlights: [
			"200+ countries geographic tracking",
			"AI bot analytics bundled with privacy-first web analytics",
			"Acquired for $85,000",
		],
		notes: "Acquired — see TrustMRR listing",
	},
	{
		slug: "rank-ai",
		name: "Rank.ai",
		domain: "rank.ai",
		url: "https://www.rank.ai/",
		tagline: "AI-powered content creation and ranking platform",
		description:
			"Rank.ai combines AI content generation with rank tracking, offering tools to create content optimized for both traditional search and AI platforms. Their focus is on helping brands publish content that gets cited by AI search engines.",
		category: "content",
		ahrefsDR: 47,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			brandMentionTracking: true,
			keywordResearch: true,
			contentGeneration: true,
		},
		pricing: { hasFree: false, hasEnterprise: false },
		highlights: [
			"Combined content creation + rank tracking",
			"Optimizes content for AI citation",
		],
	},
	{
		slug: "quattr",
		name: "Quattr",
		domain: "quattr.com",
		url: "https://www.quattr.com/",
		tagline: "AI-native SEO/AEO/GEO unified platform with GIGA AI Agent",
		description:
			"Quattr offers a unified SEO, AEO, and GEO platform powered by their GIGA AI Agent. Their approach combines traditional search optimization with AI visibility tracking and content generation. The GIGA agent automates content analysis, optimization, and creation workflows.",
		category: "content",
		ahrefsDR: 46,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			brandMentionTracking: true,
			siteAudits: true,
			keywordResearch: true,
			contentGeneration: true,
		},
		pricing: { hasFree: false, hasEnterprise: true },
		highlights: [
			"GIGA AI Agent for automated content workflows",
			"Unified SEO + AEO + GEO platform",
		],
	},
	{
		slug: "gumshoe",
		name: "Gumshoe",
		domain: "gumshoe.ai",
		url: "https://www.gumshoe.ai/",
		tagline: "AI visibility intelligence platform",
		description:
			"Gumshoe provides AI visibility intelligence, helping brands understand how they appear across AI search platforms. Their platform monitors mentions, tracks citations, and provides competitive analysis for AI search results.",
		category: "tracking",
		ahrefsDR: 45,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			competitorBenchmarking: true,
			brandMentionTracking: true,
		},
		pricing: { hasFree: false, hasEnterprise: false },
		highlights: ["AI visibility intelligence focus"],
	},
	{
		slug: "limy",
		name: "Limy",
		domain: "limy.ai",
		url: "https://www.limy.ai/",
		tagline: "B2A (Business to Agents) with AI revenue tracking",
		description:
			"Limy introduces the B2A (Business to Agents) concept, focusing on tracking revenue from AI referrals rather than just visibility. Their platform measures AI traffic attribution, conversion tracking, and provides optimization steps to improve AI-driven revenue. Unique in tying visibility directly to business outcomes.",
		category: "tracking",
		ahrefsDR: 44,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			brandMentionTracking: true,
			sentimentAnalysis: true,
			actionRecommendations: true,
		},
		pricing: { hasFree: false, hasEnterprise: false },
		highlights: [
			"B2A (Business to Agents) concept",
			"AI revenue and conversion tracking",
			"Ties visibility to business outcomes",
		],
	},
	{
		slug: "bear-ai",
		name: "Bear AI",
		domain: "usebear.ai",
		url: "https://www.usebear.ai/",
		tagline: "Blog Agent for AI-optimized content and visibility tracking",
		description:
			"Bear AI offers a Blog Agent that creates AI-optimized content designed to be cited by language models. Their platform combines content generation with visibility tracking, helping brands produce and monitor content that improves AI search presence.",
		category: "content",
		ahrefsDR: 41,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			brandMentionTracking: true,
			contentGeneration: true,
		},
		pricing: { hasFree: false, hasEnterprise: false },
		highlights: [
			"Blog Agent for AI-optimized content",
			"Combined content creation + tracking",
		],
	},
	{
		slug: "getmint",
		name: "GetMint",
		domain: "getmint.ai",
		url: "https://getmint.ai/",
		tagline: "150K+ partner media distribution network for AI citations",
		description:
			"GetMint takes a unique approach to AI visibility by offering content distribution through a network of 150,000+ partner media outlets. Their theory: publishing content through trusted media channels influences which sources AI models cite. Combines tracking with active citation building through media distribution.",
		category: "content",
		ahrefsDR: 39,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			brandMentionTracking: true,
			contentGeneration: true,
		},
		pricing: { hasFree: false, hasEnterprise: true },
		highlights: [
			"150,000+ partner media distribution network",
			"Active citation building through media placement",
		],
	},
	{
		slug: "aiclicks",
		name: "AIclicks",
		domain: "aiclicks.io",
		url: "https://aiclicks.io/",
		tagline: "Done-for-you action plans with AI agents",
		description:
			"AIclicks provides done-for-you action plans powered by AI agents that identify visibility gaps and competitor opportunities. Their full-service approach means they don't just show you data — they create specific action plans for improving AI search presence.",
		category: "tracking",
		ahrefsDR: 38,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			competitorBenchmarking: true,
			brandMentionTracking: true,
			actionRecommendations: true,
		},
		pricing: { hasFree: false, hasEnterprise: false },
		highlights: [
			"Done-for-you action plans",
			"AI agents for competitor gap analysis",
		],
	},
	{
		slug: "searchable",
		name: "Searchable",
		domain: "searchable.com",
		url: "https://www.searchable.com/",
		tagline: "AI search visibility platform",
		description:
			"Searchable offers an AI search visibility platform that monitors how brands appear across AI-powered search engines. Their platform tracks mentions, citations, and competitive positioning in AI search results.",
		category: "tracking",
		ahrefsDR: 37,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			brandMentionTracking: true,
		},
		pricing: { hasFree: false, hasEnterprise: false },
		highlights: ["AI search visibility monitoring"],
	},
	{
		slug: "llm-pulse",
		name: "LLM Pulse",
		domain: "llmpulse.ai",
		url: "https://llmpulse.ai/",
		tagline: "AI visibility with prompt suggestions and Looker Studio connector",
		description:
			"LLM Pulse tracks AI visibility with AI prompt suggestions, sentiment tracking, and a Looker Studio connector for custom reporting. Their platform provides real-time alerts when visibility changes and helps discover relevant prompts to track.",
		category: "tracking",
		ahrefsDR: 37,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			brandMentionTracking: true,
			sentimentAnalysis: true,
			keywordResearch: true,
			emailAlerts: true,
			biConnectors: true,
		},
		pricing: { hasFree: false, hasEnterprise: false },
		highlights: [
			"AI prompt suggestions for query discovery",
			"Looker Studio connector",
			"Real-time visibility change alerts",
		],
	},
	{
		slug: "ai-peekaboo",
		name: "AI Peekaboo",
		domain: "aipeekaboo.com",
		url: "https://www.aipeekaboo.com/",
		tagline: "White-label GEO competitive intelligence for agencies",
		description:
			"AI Peekaboo offers white-label reports and GEO competitive intelligence designed for agencies and brand+agency partnerships. Their platform provides AI visibility tracking with branded reporting capabilities.",
		category: "tracking",
		ahrefsDR: 37,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			competitorBenchmarking: true,
			brandMentionTracking: true,
			whiteLabelAgency: true,
		},
		pricing: { hasFree: false, hasEnterprise: true },
		highlights: [
			"White-label reports for agencies",
			"GEO competitive intelligence",
		],
	},
	{
		slug: "checkthat",
		name: "CheckThat",
		domain: "checkthat.ai",
		url: "https://checkthat.ai/",
		tagline: "No cold start AEO tracking, driving growth for GrowthX",
		description:
			"CheckThat offers AI visibility tracking with the key advantage of no cold start — you get data from the first query. Built as a lead generation tool for GrowthX, their consulting service. Includes SEO-focused features alongside AI tracking.",
		category: "tracking",
		ahrefsDR: 36,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			brandMentionTracking: true,
			siteAudits: true,
		},
		pricing: { hasFree: true, hasEnterprise: false },
		highlights: [
			"No cold start — instant data from first query",
			"Drives leads for GrowthX consulting",
			"SEO features alongside AI tracking",
		],
		notes: "Used as a lead gen tool for https://growthx.ai/",
	},
	{
		slug: "bluefish-ai",
		name: "BluefishAI",
		domain: "bluefishai.com",
		url: "https://www.bluefishai.com/",
		tagline: "Enterprise AI Commerce platform for Fortune 500",
		description:
			"BluefishAI focuses on enterprise AI commerce, helping Fortune 500 brands optimize their presence in AI-powered shopping experiences. Their platform monitors product visibility in AI shopping features and helps optimize product data for AI consumption.",
		category: "ecommerce",
		ahrefsDR: 35,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			brandMentionTracking: true,
			shoppingTracking: true,
			dataExportApi: true,
		},
		pricing: { hasFree: false, hasEnterprise: true },
		highlights: [
			"Enterprise Fortune 500 focus",
			"AI Commerce optimization",
		],
	},
	{
		slug: "parse",
		name: "Parse",
		domain: "parse.gl",
		url: "https://parse.gl/",
		tagline: "219K+ brands database with peer visibility tracking",
		description:
			"Parse maintains a database of over 219,000 brands, providing peer visibility analysis that shows how you compare against similar brands in AI search. Their large tracking dataset enables industry-level benchmarking and competitive analysis.",
		category: "tracking",
		ahrefsDR: 35,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			competitorBenchmarking: true,
			brandMentionTracking: true,
		},
		pricing: { hasFree: false, hasEnterprise: false },
		highlights: [
			"219,000+ brands database",
			"Peer visibility and industry benchmarking",
		],
	},
	{
		slug: "amionai",
		name: "AmIOnAI",
		domain: "amionai.com",
		url: "https://www.amionai.com/",
		tagline: "Weekly action plans with impact tracking and 'The Index' leaderboards",
		description:
			"AmIOnAI serves 7,000+ marketers with AI visibility tracking centered around actionable weekly plans. Their standout features include 'The Index' — public AI visibility leaderboards by category — and action plans with specific Reddit/LinkedIn/content recommendations and impact tracking.",
		category: "tracking",
		ahrefsDR: 34,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			competitorBenchmarking: true,
			brandMentionTracking: true,
			geographicTracking: true,
			socialMediaTracking: true,
			actionRecommendations: true,
			dataExportApi: true,
			whiteLabelAgency: true,
		},
		pricing: { hasFree: false, hasEnterprise: true },
		highlights: [
			"7,000+ marketers on platform",
			"'The Index' — public AI visibility leaderboards",
			"Weekly action plans with impact tracking",
		],
	},
	{
		slug: "lorelight",
		name: "Lorelight",
		domain: "growwithless.com",
		url: "https://growwithless.com/shutting-down-lorelight/",
		tagline: "AI visibility startup (shutting down)",
		description:
			"Lorelight was an AI visibility tracking platform that is shutting down. Their experience highlights the challenges of building in the AEO space — despite growing interest in AI search optimization, the competitive dynamics and unit economics proved difficult.",
		category: "tracking",
		ahrefsDR: 33,
		status: "shutting-down",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			brandMentionTracking: true,
		},
		pricing: { hasFree: false, hasEnterprise: false },
		highlights: ["Shutting down — documented lessons learned publicly"],
		notes: "Shutting down. Public postmortem available.",
	},
	{
		slug: "showupinai",
		name: "ShowUpInAI",
		domain: "showupinai.com",
		url: "https://showupinai.com/",
		tagline: "IndexNow integration for faster AI indexing",
		description:
			"ShowUpInAI takes a unique approach by focusing on getting your content indexed by AI search engines faster. Their core feature is automatic IndexNow submission to Bing (which powers ChatGPT, Copilot, and Perplexity). Also offers an AI View feature showing how AI crawlers see your pages.",
		category: "tracking",
		ahrefsDR: 33,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			brandMentionTracking: true,
			siteAudits: true,
		},
		pricing: { hasFree: true, hasEnterprise: false },
		highlights: [
			"IndexNow integration for faster AI indexing",
			"AI View — see how AI crawlers interpret your pages",
			"Bing-focused for ChatGPT/Copilot/Perplexity",
		],
	},
	{
		slug: "getcito",
		name: "GetCito",
		domain: "getcito.com",
		url: "https://getcito.com/",
		tagline: "Open-source (MIT) AEO tool with AI Crawlability Clinic",
		description:
			"GetCito is one of the few open-source AEO tools, licensed under MIT. Their AI Crawlability Clinic evaluates how well AI bots can access and understand your content. They also offer GEO playbooks and consulting services for agencies.",
		category: "open-source",
		ahrefsDR: 27,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			brandMentionTracking: true,
			geographicTracking: true,
			siteAudits: true,
			openSource: true,
			whiteLabelAgency: true,
		},
		pricing: { hasFree: true, hasEnterprise: true },
		highlights: [
			"Open source (MIT license)",
			"AI Crawlability Clinic",
			"GEO playbooks for agencies",
		],
	},
	{
		slug: "meridian",
		name: "Meridian",
		domain: "trymeridian.com",
		url: "https://trymeridian.com/",
		tagline: "AI content optimization with geographic tracking",
		description:
			"Meridian offers AI visibility tracking with a focus on content optimization and geographic targeting. Their platform helps brands understand how AI search results vary by location and provides content recommendations tailored to regional audiences.",
		category: "tracking",
		ahrefsDR: 25,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			brandMentionTracking: true,
			geographicTracking: true,
			contentGeneration: true,
		},
		pricing: { hasFree: false, hasEnterprise: false },
		highlights: [
			"Geographic targeting for AI visibility",
			"Content optimization recommendations",
		],
	},
	{
		slug: "peasy",
		name: "Peasy",
		domain: "peasy.so",
		url: "https://peasy.so/",
		tagline: "Server-side AI traffic analytics, privacy-first and cookie-free",
		description:
			"Peasy focuses on server-side AI traffic analytics, providing cookie-free and GDPR-compliant tracking of visitors arriving from AI platforms. Their privacy-first approach measures AI referral traffic and conversions without cookies or client-side scripts.",
		category: "tracking",
		ahrefsDR: 25,
		status: "active",
		features: {
			visibilityScore: true,
			brandMentionTracking: true,
			crawlerAnalytics: true,
		},
		pricing: { hasFree: true, hasEnterprise: false },
		highlights: [
			"Server-side, cookie-free analytics",
			"Privacy-first GDPR-compliant tracking",
			"AI referral traffic attribution",
		],
	},
	{
		slug: "flip-aeo",
		name: "Flip AEO",
		domain: "flipaeo.com",
		url: "https://flipaeo.com/",
		tagline: "AEO tracking and optimization platform",
		description:
			"Flip AEO provides AI visibility tracking and optimization tools, helping brands monitor and improve their presence in AI search results. Their platform covers the core AEO tracking features with an optimization-focused approach.",
		category: "tracking",
		ahrefsDR: 20,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			brandMentionTracking: true,
		},
		pricing: { hasFree: false, hasEnterprise: false },
		highlights: ["Optimization-focused AEO platform"],
	},
	{
		slug: "radarkit",
		name: "Radarkit",
		domain: "radarkit.ai",
		url: "https://radarkit.ai/",
		tagline: "50+ countries with LLM referral traffic and content crafting",
		description:
			"Radarkit offers AI visibility tracking across 50+ countries with LLM referral traffic measurement. Their platform includes sentiment analysis, multi-language content tracking, and content crafting from citation analysis. Provides visibility into how AI platforms recommend your brand globally.",
		category: "tracking",
		ahrefsDR: 16,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			brandMentionTracking: true,
			sentimentAnalysis: true,
			geographicTracking: true,
			multiLanguage: true,
			contentGeneration: true,
		},
		pricing: { hasFree: false, hasEnterprise: false },
		highlights: [
			"50+ countries geographic tracking",
			"LLM referral traffic measurement",
			"Content crafting from citation analysis",
		],
	},
	{
		slug: "seozast",
		name: "SEOzast",
		domain: "seozast.com",
		url: "https://www.seozast.com/",
		tagline: "Ultra-affordable AEO at $19.99/mo with AI content generation",
		description:
			"SEOzast offers one of the most affordable AEO platforms at $19.99/month, targeting developers and small businesses. Includes AI content generation, Bing auto-indexing, and GitHub publishing integration. Developer-focused approach to AEO.",
		category: "content",
		ahrefsDR: 10,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			brandMentionTracking: true,
			siteAudits: true,
			contentGeneration: true,
		},
		pricing: { hasFree: false, startingPrice: "$19.99/mo", hasEnterprise: false },
		highlights: [
			"Ultra-affordable at $19.99/month",
			"Bing auto-indexing",
			"Developer-focused with GitHub integration",
		],
	},
	{
		slug: "anvil",
		name: "Anvil",
		domain: "joinanvil.com",
		url: "https://joinanvil.com/",
		tagline: "AEO platform for brands",
		description:
			"Anvil provides AI visibility tracking and optimization for brands looking to improve their presence in AI search results. Their platform offers core AEO tracking features with a focus on brand visibility metrics.",
		category: "tracking",
		ahrefsDR: 10,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			brandMentionTracking: true,
		},
		pricing: { hasFree: false, hasEnterprise: false },
		highlights: ["Brand-focused AEO tracking"],
	},
	{
		slug: "petra-labs",
		name: "Petra Labs",
		domain: "petralabs.ai",
		url: "https://www.petralabs.ai/",
		tagline: "AI visibility monitoring platform",
		description:
			"Petra Labs offers an AI visibility monitoring platform that tracks how brands appear in AI-powered search engines. Their platform provides visibility scoring and brand mention tracking across major AI platforms.",
		category: "tracking",
		ahrefsDR: 7,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			brandMentionTracking: true,
		},
		pricing: { hasFree: false, hasEnterprise: false },
		highlights: ["AI visibility monitoring platform"],
	},
	{
		slug: "genrankengine",
		name: "GenRankEngine",
		domain: "genrankengine.com",
		url: "https://www.genrankengine.com/",
		tagline: "SaaS-focused with Displacement Reports on TrustViews traffic",
		description:
			"GenRankEngine targets SaaS companies specifically, offering Displacement Reports that show which competitors are being recommended instead of you. Uniquely uses TrustViews as a traffic baseline for measuring AI visibility impact.",
		category: "tracking",
		ahrefsDR: 6,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			competitorBenchmarking: true,
			brandMentionTracking: true,
			contentGeneration: true,
		},
		pricing: { hasFree: true, hasEnterprise: false },
		highlights: [
			"SaaS-focused niche",
			"Displacement Reports — who's replacing you",
			"Free visibility scan",
		],
	},
	{
		slug: "searchify",
		name: "Searchify",
		domain: "searchify.ai",
		url: "https://searchify.ai/",
		tagline: "AI Search Score API with 30+ language support",
		description:
			"Searchify provides an AI Search Score API supporting 30+ languages. Their developer-focused approach provides programmatic access to AI visibility metrics with extensive language coverage.",
		category: "api-developer",
		ahrefsDR: 5,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			brandMentionTracking: true,
			multiLanguage: true,
			actionRecommendations: true,
			dataExportApi: true,
		},
		pricing: { hasFree: false, hasEnterprise: false },
		highlights: [
			"30+ language support",
			"AI Search Score API",
			"Developer-focused approach",
		],
	},
	{
		slug: "datagum",
		name: "Datagum",
		domain: "datagum.ai",
		url: "https://datagum.ai/",
		tagline: "Auto brand book, JSON-LD generator, and citation analyzer",
		description:
			"Datagum offers free tools including a JSON-LD schema generator, citation analyzer, and auto brand book generator. Their affordable approach to AEO focuses on helping brands improve their structured data and AI discoverability through free audit tools.",
		category: "tracking",
		ahrefsDR: 4,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			brandMentionTracking: true,
			siteAudits: true,
		},
		pricing: { hasFree: true, hasEnterprise: false },
		highlights: [
			"Free JSON-LD schema generator",
			"Citation analyzer tool",
			"Auto brand book generator",
		],
	},
	{
		slug: "ecom-ai",
		name: "Ecom.ai",
		domain: "ecom.ai",
		url: "https://ecom.ai/",
		tagline: "E-commerce AEO with schema injection services",
		description:
			"Ecom.ai specializes in AEO for e-commerce businesses, offering done-for-you services including schema injection, product data optimization, and AI shopping visibility tracking. Their approach combines tooling with managed services for online retailers.",
		category: "ecommerce",
		ahrefsDR: 3,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			brandMentionTracking: true,
			shoppingTracking: true,
			siteAudits: true,
		},
		pricing: { hasFree: false, hasEnterprise: true },
		highlights: [
			"E-commerce focused AEO",
			"Done-for-you schema injection",
			"AI shopping visibility tracking",
		],
	},
	{
		slug: "lantern",
		name: "Lantern",
		domain: "asklantern.com",
		url: "https://www.asklantern.com/",
		tagline: "AI traffic attribution with traditional SEO integration",
		description:
			"Lantern focuses on AI traffic attribution, helping brands understand and measure website visitors arriving from AI platforms. Their platform combines AI referral tracking with traditional SEO metrics for a unified view of search performance.",
		category: "tracking",
		ahrefsDR: 3,
		status: "active",
		features: {
			visibilityScore: true,
			brandMentionTracking: true,
			crawlerAnalytics: true,
			dataExportApi: true,
		},
		pricing: { hasFree: false, hasEnterprise: false },
		highlights: [
			"AI traffic attribution focus",
			"Unified AI + traditional SEO analytics",
		],
	},
	{
		slug: "thirdeye",
		name: "Thirdeye",
		domain: "usethirdeye.com",
		url: "https://usethirdeye.com/",
		tagline: "Visibility spike alerts and negative mention detection",
		description:
			"Thirdeye focuses on real-time monitoring with visibility spike alerts and negative mention detection. Their platform tracks AI visibility across major platforms and provides instant alerts when significant changes occur, helping brands respond quickly to visibility shifts.",
		category: "tracking",
		ahrefsDR: 3,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			brandMentionTracking: true,
			sentimentAnalysis: true,
			emailAlerts: true,
		},
		pricing: { hasFree: false, hasEnterprise: false },
		highlights: [
			"Real-time visibility spike alerts",
			"Negative mention detection",
			"Instant alert system for visibility changes",
		],
	},
	{
		slug: "heeb",
		name: "Heeb",
		domain: "heeb.ai",
		url: "https://heeb.ai/",
		tagline: "LLM Mentions API for developers and tool builders",
		description:
			"Heeb offers an LLM Mentions API designed for developers and tool builders who want to integrate AI visibility data into their own products. Their API-first approach provides programmatic access to brand mention data with sentiment analysis and location-targeted queries.",
		category: "api-developer",
		ahrefsDR: 3,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			brandMentionTracking: true,
			sentimentAnalysis: true,
			geographicTracking: true,
			dataExportApi: true,
		},
		pricing: { hasFree: false, hasEnterprise: false },
		highlights: [
			"LLM Mentions API for developers",
			"Location-targeted queries",
			"Useful for influencing API design decisions",
		],
		notes: "Could use to influence API design",
	},
	{
		slug: "espygo",
		name: "EspyGo",
		domain: "espy-go.com",
		url: "https://espy-go.com/",
		tagline: "Content strategist with SEO score and AEO tracking",
		description:
			"EspyGo provides content strategy tools with an SEO score alongside AEO tracking capabilities. Their platform helps brands understand content performance in both traditional and AI search, with optimization recommendations.",
		category: "content",
		ahrefsDR: 2,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			brandMentionTracking: true,
			siteAudits: true,
			contentGeneration: true,
		},
		pricing: { hasFree: false, hasEnterprise: false },
		highlights: [
			"Content strategist approach",
			"Combined SEO score and AEO tracking",
		],
	},
	{
		slug: "naryai",
		name: "NaryAI",
		domain: "naryai.com",
		url: "https://naryai.com/",
		tagline: "ROI estimates on recommendations with crisis prevention",
		description:
			"NaryAI provides AI visibility tracking with ROI estimates on their recommendations, helping brands understand the potential business impact of optimization actions. Their platform includes crisis prevention features that alert teams before visibility issues escalate.",
		category: "tracking",
		ahrefsDR: 1,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			brandMentionTracking: true,
			actionRecommendations: true,
			emailAlerts: true,
		},
		pricing: { hasFree: false, hasEnterprise: false },
		highlights: [
			"ROI estimates on recommendations",
			"Crisis prevention alerts",
		],
	},
	{
		slug: "bourd",
		name: "Bourd",
		domain: "bourd.dev",
		url: "https://bourd.dev/",
		tagline: "Developer-focused AEO monitoring tool",
		description:
			"Bourd is a developer-focused AEO monitoring tool that provides AI visibility tracking through a technical, code-first interface. Designed for developers who want to integrate AI search monitoring into their workflows.",
		category: "tracking",
		ahrefsDR: 1,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			brandMentionTracking: true,
			dataExportApi: true,
		},
		pricing: { hasFree: false, hasEnterprise: false },
		highlights: ["Developer-focused interface"],
	},
	{
		slug: "visble",
		name: "Visble",
		domain: "visble.ai",
		url: "https://visble.ai/",
		tagline: "AEO experimentation lab with affordable pricing ($29 starter)",
		description:
			"Visble offers an AEO experimentation lab where brands can test and measure different content strategies' impact on AI visibility. Their affordable $29 starter plan and AI content analysis features make them accessible for smaller teams. Also offers a free visibility report.",
		category: "tracking",
		ahrefsDR: 1,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			brandMentionTracking: true,
			siteAudits: true,
		},
		pricing: { hasFree: true, startingPrice: "$29/mo", hasEnterprise: false },
		highlights: [
			"AEO experimentation lab",
			"Affordable $29/month starter plan",
			"Free visibility report available",
		],
	},
	{
		slug: "ai-serp-tracker",
		name: "AI SERP Tracker",
		domain: "aiserptracker.com",
		url: "https://www.aiserptracker.com/",
		tagline: "AI search result position tracking",
		description:
			"AI SERP Tracker monitors brand positions in AI-generated search results. Their platform tracks how your brand appears in AI Overviews, featured snippets, and other AI-enhanced search features.",
		category: "tracking",
		ahrefsDR: 0,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			brandMentionTracking: true,
		},
		pricing: { hasFree: false, hasEnterprise: false },
		highlights: ["AI search result position tracking"],
	},
	{
		slug: "sixthshop",
		name: "Sixthshop",
		domain: "sixthshop.com",
		url: "https://www.sixthshop.com/",
		tagline: "AI Shopping Visibility Index for Shopify, Amazon, WooCommerce",
		description:
			"Sixthshop focuses on AI shopping visibility, offering an AI Shopping Visibility Index for e-commerce platforms. They track product visibility across Shopify, Amazon, and WooCommerce when AI platforms recommend shopping options.",
		category: "ecommerce",
		ahrefsDR: 0,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			brandMentionTracking: true,
			shoppingTracking: true,
		},
		pricing: { hasFree: false, hasEnterprise: false },
		highlights: [
			"AI Shopping Visibility Index",
			"Shopify, Amazon, WooCommerce tracking",
			"E-commerce focused",
		],
	},
	{
		slug: "chatgeo",
		name: "ChatGEO",
		domain: "chatgeo.xyz",
		url: "https://chatgeo.xyz/",
		tagline: "Hybrid SEO+GEO engine with entity density optimization",
		description:
			"ChatGEO provides a hybrid SEO and GEO engine that optimizes content for both traditional and AI search through entity density analysis. Their free GEO scan helps brands understand their current AI visibility status.",
		category: "content",
		ahrefsDR: 0,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			brandMentionTracking: true,
			siteAudits: true,
			contentGeneration: true,
		},
		pricing: { hasFree: true, hasEnterprise: false },
		highlights: [
			"Free GEO scan",
			"Entity density optimization",
			"Hybrid SEO + GEO approach",
		],
		notes: "See TrustMRR listing",
	},
	{
		slug: "allsearch",
		name: "AllSearch",
		domain: "allsearch.io",
		url: "https://allsearch.io/",
		tagline: "GEO opportunities with prompt intelligence and actionable alerts",
		description:
			"AllSearch provides AI visibility tracking with a focus on identifying GEO opportunities and actionable alerts. Their prompt intelligence features help discover relevant queries, while their alert system notifies teams of significant visibility changes.",
		category: "tracking",
		ahrefsDR: 0,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			brandMentionTracking: true,
			actionRecommendations: true,
			emailAlerts: true,
		},
		pricing: { hasFree: false, startingPrice: "$299/mo", hasEnterprise: false },
		highlights: [
			"GEO opportunity identification",
			"Prompt intelligence and discovery",
			"Actionable visibility alerts",
		],
	},
	{
		slug: "mentionstack",
		name: "MentionStack",
		domain: "mentionstack.com",
		url: "https://www.mentionstack.com/",
		tagline: "GEO optimization with Reddit and Quora management",
		description:
			"MentionStack combines GEO optimization with social media management for Reddit and Quora — two platforms that heavily influence AI search citations. Their approach recognizes that managing your brand presence on these forums directly impacts AI visibility.",
		category: "tracking",
		ahrefsDR: 0,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			brandMentionTracking: true,
			socialMediaTracking: true,
		},
		pricing: { hasFree: false, hasEnterprise: false },
		highlights: [
			"Reddit and Quora management for AI influence",
			"GEO + social media optimization",
		],
	},
	{
		slug: "searchone",
		name: "SearchOne",
		domain: "searchone.ai",
		url: "https://searchone.ai/",
		tagline: "GEO proxy and AI crawler visibility checker",
		description:
			"SearchOne offers a GEO proxy tool and AI crawler visibility checker that helps brands understand how AI search engines access and interpret their content. Their approach focuses on the technical aspects of AI discoverability.",
		category: "tracking",
		ahrefsDR: 0,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			brandMentionTracking: true,
			crawlerAnalytics: true,
			siteAudits: true,
		},
		pricing: { hasFree: false, hasEnterprise: false },
		highlights: [
			"GEO proxy tool",
			"AI crawler visibility checker",
		],
	},
	{
		slug: "rankgpt",
		name: "RankGPT",
		domain: "rankgpt.com",
		url: "https://rankgpt.com/",
		tagline: "AI visibility with citation builder and auto-publish content",
		description:
			"RankGPT combines AI visibility tracking with a citation builder that automatically publishes content designed to be cited by AI platforms. Their auto-publish feature creates and distributes content at scale to build AI citations.",
		category: "content",
		ahrefsDR: 0,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			citationAnalytics: true,
			brandMentionTracking: true,
			contentGeneration: true,
		},
		pricing: { hasFree: false, hasEnterprise: false },
		highlights: [
			"Citation builder tool",
			"Auto-publish content for AI citations",
		],
	},
	{
		slug: "gego-analytics",
		name: "Gego Analytics",
		domain: "ai2hu.github.io",
		url: "https://ai2hu.github.io/gego-analytics/",
		tagline: "Open-source AEO analytics tool",
		description:
			"Gego Analytics is an open-source AEO analytics tool hosted on GitHub. It provides basic AI visibility tracking capabilities for developers who want to self-host their own AEO monitoring without proprietary dependencies.",
		category: "open-source",
		ahrefsDR: 0,
		status: "active",
		features: {
			multiLlmTracking: true,
			visibilityScore: true,
			brandMentionTracking: true,
			dataExportApi: true,
			openSource: true,
		},
		pricing: { hasFree: true, hasEnterprise: false },
		highlights: [
			"Open-source on GitHub",
			"Self-hostable AEO analytics",
		],
	},
	{
		slug: "microsoft-ads",
		name: "Microsoft Ads",
		domain: "about.ads.microsoft.com",
		url: "https://about.ads.microsoft.com/en/blog/post/october-2025/optimizing-your-content-for-inclusion-in-ai-search-answers",
		tagline: "Microsoft's official guidance on optimizing for AI search answers",
		description:
			"Microsoft Ads has published official guidance on optimizing content for inclusion in AI search answers, covering Copilot and Bing AI. While not a standalone product, their recommendations carry weight as they directly control the AI search engine that powers multiple AI assistants.",
		category: "other",
		ahrefsDR: 0,
		status: "active",
		features: {},
		highlights: [
			"Official Microsoft guidance for Copilot/Bing AI",
			"Not a standalone product",
		],
		notes:
			"Blog post with official optimization guidance, not a competitor product",
	},
];

export function getCompetitorBySlug(slug: string): Competitor | undefined {
	return competitors.find((c) => c.slug === slug);
}

export function getComparisonSlug(competitor: Competitor): string {
	return `elmo-vs-${competitor.slug}`;
}

const maxDRSquared = Math.max(...competitors.map((c) => c.ahrefsDR * c.ahrefsDR));

const popularityMap = new Map(
	competitors.map((c) => [
		c.slug,
		maxDRSquared > 0
			? ((c.ahrefsDR * c.ahrefsDR) / maxDRSquared) * 5
			: 0,
	]),
);

/** Popularity score normalized to 0–5, derived from squared domain authority. */
export function getPopularity(competitor: Competitor): number {
	return popularityMap.get(competitor.slug) ?? 0;
}

export function formatPopularity(competitor: Competitor): string {
	const score = getPopularity(competitor);
	if (score >= 0.1) return score.toFixed(1);
	if (score >= 0.01) return score.toFixed(2);
	return "<0.01";
}

export function getPopularityGrade(competitor: Competitor): string {
	const score = getPopularity(competitor);
	if (score >= 3) return "A";
	if (score >= 1.5) return "B";
	if (score >= 0.5) return "C";
	if (score >= 0.1) return "D";
	return "F";
}
