export { getComparisonFaqs, getComparisonVerdict } from "./content";

export {
	competitors,
	getComparisonSlug,
	getCompetitorBySlug,
	getPopularityGrade,
	getPopularityRank,
	sortedCompetitors,
} from "./data";
export {
	CATEGORY_HEADINGS,
	CATEGORY_SLUGS,
	comparePairCompetitors,
	comparePairSlug,
	comparePairs,
	compareSetSlug,
	compareSets,
	FEATURE_SLUGS,
	getAlternatives,
	getAlternativesFaqs,
	getAlternativesVerdict,
	getCategoryBySlug,
	getCategoryElmoPitch,
	getCategoryFaqs,
	getCategoryVerdict,
	getCompareEntry,
	getCompareFaqs,
	getComparePair,
	getCompareSet,
	getCompareVerdict,
	getFeatureFaqs,
	getFeatureKeyBySlug,
	getFeatureVerdict,
	getPairFaqs,
	getPairVerdict,
	getSetFaqs,
	getSetVerdict,
	indexableCategories,
	indexableFeatureKeys,
	indexedCompetitors,
	isIndexed,
	MIN_TOOLS_FOR_FEATURE_PAGE,
	openSourceTools,
	toolsInCategory,
	toolsWithFeature,
} from "./directory";
export {
	ALL_FEATURE_KEYS,
	CATEGORY_LABELS,
	type Competitor,
	type CompetitorCategory,
	ELMO_FEATURES,
	FEATURE_CATEGORIES,
	type FeatureCategory,
	type FeatureDefinition,
	type FeatureKey,
	getFeatureDescription,
	getFeatureLabel,
	getFeatureSearchTerm,
	getScreenshotUrl,
	isLowDR,
	LOW_DR_THRESHOLD,
} from "./types";
