// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         competitorId: "competitorId"
 *     }
 */
export interface DeleteCompetitorRequest {
    /** Competitor identifier (UUID) */
    competitorId: string;
}
