// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         competitorId: "competitorId"
 *     }
 */
export interface UpdateCompetitorRequest {
    /** Competitor identifier (UUID) */
    competitorId: string;
    name?: string;
    domains?: string[];
    aliases?: string[];
}
