// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Elmo from "../../../index.js";

export declare namespace PromptsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Manage brand prompts
 */
export class PromptsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<PromptsClient.Options>;

    constructor(options: PromptsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Retrieve a paginated list of all prompts across all brands
     *
     * @param {Elmo.ListPromptsRequest} request
     * @param {PromptsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Elmo.UnauthorizedError}
     * @throws {@link Elmo.ForbiddenError}
     * @throws {@link Elmo.TooManyRequestsError}
     * @throws {@link Elmo.InternalServerError}
     * @throws {@link errors.ElmoError}
     * @throws {@link errors.ElmoTimeoutError}
     *
     * @example
     *     await client.prompts.listPrompts()
     */
    public listPrompts(
        request: Elmo.ListPromptsRequest = {},
        requestOptions?: PromptsClient.RequestOptions,
    ): core.HttpResponsePromise<Elmo.ListPromptsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listPrompts(request, requestOptions));
    }

    private async __listPrompts(
        request: Elmo.ListPromptsRequest = {},
        requestOptions?: PromptsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Elmo.ListPromptsResponse>> {
        const { brandId, page, limit, enabled, tags, q } = request;
        const _queryParams: Record<string, unknown> = {
            brandId,
            page,
            limit,
            enabled,
            tags,
            q,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ElmoEnvironment.Default,
                "prompts",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Elmo.ListPromptsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Elmo.UnauthorizedError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 403:
                    throw new Elmo.ForbiddenError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 429:
                    throw new Elmo.TooManyRequestsError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 500:
                    throw new Elmo.InternalServerError(_response.error.body as Elmo.Error_, _response.rawResponse);
                default:
                    throw new errors.ElmoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/prompts");
    }

    /**
     * Create a new prompt for a brand. This will automatically schedule the prompt for execution.
     *
     * @param {Elmo.CreatePromptRequest} request
     * @param {PromptsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Elmo.BadRequestError}
     * @throws {@link Elmo.UnauthorizedError}
     * @throws {@link Elmo.PaymentRequiredError}
     * @throws {@link Elmo.ForbiddenError}
     * @throws {@link Elmo.ConflictError}
     * @throws {@link Elmo.TooManyRequestsError}
     * @throws {@link Elmo.InternalServerError}
     * @throws {@link errors.ElmoError}
     * @throws {@link errors.ElmoTimeoutError}
     *
     * @example
     *     await client.prompts.createPrompt({
     *         brandId: "brandId",
     *         value: "value"
     *     })
     */
    public createPrompt(
        request: Elmo.CreatePromptRequest,
        requestOptions?: PromptsClient.RequestOptions,
    ): core.HttpResponsePromise<Elmo.Prompt> {
        return core.HttpResponsePromise.fromPromise(this.__createPrompt(request, requestOptions));
    }

    private async __createPrompt(
        request: Elmo.CreatePromptRequest,
        requestOptions?: PromptsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Elmo.Prompt>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ElmoEnvironment.Default,
                "prompts",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Elmo.Prompt, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Elmo.BadRequestError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 401:
                    throw new Elmo.UnauthorizedError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 402:
                    throw new Elmo.PaymentRequiredError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 403:
                    throw new Elmo.ForbiddenError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 409:
                    throw new Elmo.ConflictError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 429:
                    throw new Elmo.TooManyRequestsError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 500:
                    throw new Elmo.InternalServerError(_response.error.body as Elmo.Error_, _response.rawResponse);
                default:
                    throw new errors.ElmoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/prompts");
    }

    /**
     * Retrieve a specific prompt by ID
     *
     * @param {Elmo.GetPromptRequest} request
     * @param {PromptsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Elmo.BadRequestError}
     * @throws {@link Elmo.UnauthorizedError}
     * @throws {@link Elmo.ForbiddenError}
     * @throws {@link Elmo.NotFoundError}
     * @throws {@link Elmo.TooManyRequestsError}
     * @throws {@link Elmo.InternalServerError}
     * @throws {@link errors.ElmoError}
     * @throws {@link errors.ElmoTimeoutError}
     *
     * @example
     *     await client.prompts.getPrompt({
     *         promptId: "promptId"
     *     })
     */
    public getPrompt(
        request: Elmo.GetPromptRequest,
        requestOptions?: PromptsClient.RequestOptions,
    ): core.HttpResponsePromise<Elmo.Prompt> {
        return core.HttpResponsePromise.fromPromise(this.__getPrompt(request, requestOptions));
    }

    private async __getPrompt(
        request: Elmo.GetPromptRequest,
        requestOptions?: PromptsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Elmo.Prompt>> {
        const { promptId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ElmoEnvironment.Default,
                `prompts/${core.url.encodePathParam(promptId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Elmo.Prompt, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Elmo.BadRequestError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 401:
                    throw new Elmo.UnauthorizedError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 403:
                    throw new Elmo.ForbiddenError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 404:
                    throw new Elmo.NotFoundError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 429:
                    throw new Elmo.TooManyRequestsError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 500:
                    throw new Elmo.InternalServerError(_response.error.body as Elmo.Error_, _response.rawResponse);
                default:
                    throw new errors.ElmoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/prompts/{promptId}");
    }

    /**
     * Permanently delete a prompt and cancel all related scheduled jobs. This will also cascade delete all associated prompt runs.
     *
     * Requires an instance admin key; organization keys receive `403`. The dashboard has no delete either — stop tracking a prompt with `PATCH /prompts/{promptId}` and `enabled: false`, which keeps its history and frees the plan slot.
     *
     * @param {Elmo.DeletePromptRequest} request
     * @param {PromptsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Elmo.BadRequestError}
     * @throws {@link Elmo.UnauthorizedError}
     * @throws {@link Elmo.PaymentRequiredError}
     * @throws {@link Elmo.ForbiddenError}
     * @throws {@link Elmo.NotFoundError}
     * @throws {@link Elmo.ConflictError}
     * @throws {@link Elmo.TooManyRequestsError}
     * @throws {@link Elmo.InternalServerError}
     * @throws {@link errors.ElmoError}
     * @throws {@link errors.ElmoTimeoutError}
     *
     * @example
     *     await client.prompts.deletePrompt({
     *         promptId: "promptId"
     *     })
     */
    public deletePrompt(
        request: Elmo.DeletePromptRequest,
        requestOptions?: PromptsClient.RequestOptions,
    ): core.HttpResponsePromise<Elmo.DeletePromptResponse> {
        return core.HttpResponsePromise.fromPromise(this.__deletePrompt(request, requestOptions));
    }

    private async __deletePrompt(
        request: Elmo.DeletePromptRequest,
        requestOptions?: PromptsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Elmo.DeletePromptResponse>> {
        const { promptId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ElmoEnvironment.Default,
                `prompts/${core.url.encodePathParam(promptId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Elmo.DeletePromptResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Elmo.BadRequestError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 401:
                    throw new Elmo.UnauthorizedError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 402:
                    throw new Elmo.PaymentRequiredError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 403:
                    throw new Elmo.ForbiddenError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 404:
                    throw new Elmo.NotFoundError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 409:
                    throw new Elmo.ConflictError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 429:
                    throw new Elmo.TooManyRequestsError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 500:
                    throw new Elmo.InternalServerError(_response.error.body as Elmo.Error_, _response.rawResponse);
                default:
                    throw new errors.ElmoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/prompts/{promptId}");
    }

    /**
     * Update a prompt's properties. Only provided fields will be updated. Toggling `enabled` schedules or unschedules the recurring run job.
     *
     * @param {Elmo.UpdatePromptRequest} request
     * @param {PromptsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Elmo.BadRequestError}
     * @throws {@link Elmo.UnauthorizedError}
     * @throws {@link Elmo.PaymentRequiredError}
     * @throws {@link Elmo.ForbiddenError}
     * @throws {@link Elmo.NotFoundError}
     * @throws {@link Elmo.ConflictError}
     * @throws {@link Elmo.TooManyRequestsError}
     * @throws {@link Elmo.InternalServerError}
     * @throws {@link errors.ElmoError}
     * @throws {@link errors.ElmoTimeoutError}
     *
     * @example
     *     await client.prompts.updatePrompt({
     *         promptId: "promptId"
     *     })
     */
    public updatePrompt(
        request: Elmo.UpdatePromptRequest,
        requestOptions?: PromptsClient.RequestOptions,
    ): core.HttpResponsePromise<Elmo.Prompt> {
        return core.HttpResponsePromise.fromPromise(this.__updatePrompt(request, requestOptions));
    }

    private async __updatePrompt(
        request: Elmo.UpdatePromptRequest,
        requestOptions?: PromptsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Elmo.Prompt>> {
        const { promptId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ElmoEnvironment.Default,
                `prompts/${core.url.encodePathParam(promptId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Elmo.Prompt, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Elmo.BadRequestError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 401:
                    throw new Elmo.UnauthorizedError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 402:
                    throw new Elmo.PaymentRequiredError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 403:
                    throw new Elmo.ForbiddenError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 404:
                    throw new Elmo.NotFoundError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 409:
                    throw new Elmo.ConflictError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 429:
                    throw new Elmo.TooManyRequestsError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 500:
                    throw new Elmo.InternalServerError(_response.error.body as Elmo.Error_, _response.rawResponse);
                default:
                    throw new errors.ElmoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/prompts/{promptId}");
    }
}
