// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Elmo from "../../../index.js";

export declare namespace ReportsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Generate and retrieve AI Share of Voice reports
 */
export class ReportsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ReportsClient.Options>;

    constructor(options: ReportsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Retrieve a paginated list of all reports, ordered by creation date (newest first).
     *
     * Requires an instance admin key; organization keys receive `403`.
     *
     * @param {Elmo.ListReportsRequest} request
     * @param {ReportsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Elmo.UnauthorizedError}
     * @throws {@link Elmo.ForbiddenError}
     * @throws {@link Elmo.TooManyRequestsError}
     * @throws {@link Elmo.InternalServerError}
     * @throws {@link errors.ElmoError}
     * @throws {@link errors.ElmoTimeoutError}
     *
     * @example
     *     await client.reports.listReports()
     */
    public listReports(
        request: Elmo.ListReportsRequest = {},
        requestOptions?: ReportsClient.RequestOptions,
    ): core.HttpResponsePromise<Elmo.ListReportsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listReports(request, requestOptions));
    }

    private async __listReports(
        request: Elmo.ListReportsRequest = {},
        requestOptions?: ReportsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Elmo.ListReportsResponse>> {
        const { page, limit } = request;
        const _queryParams: Record<string, unknown> = {
            page,
            limit,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ElmoEnvironment.Default,
                "reports",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Elmo.ListReportsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Elmo.UnauthorizedError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 403:
                    throw new Elmo.ForbiddenError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 429:
                    throw new Elmo.TooManyRequestsError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 500:
                    throw new Elmo.InternalServerError(_response.error.body as Elmo.Error_, _response.rawResponse);
                default:
                    throw new errors.ElmoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/reports");
    }

    /**
     * Create a new AI Share of Voice report and queue it for generation. The report will evaluate the brand across multiple AI engines (ChatGPT, Claude, Google AI) using generated and optional custom prompts.
     *
     * Requires an instance admin key; organization keys receive `403`.
     *
     * @param {Elmo.CreateReportRequest} request
     * @param {ReportsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Elmo.BadRequestError}
     * @throws {@link Elmo.UnauthorizedError}
     * @throws {@link Elmo.PaymentRequiredError}
     * @throws {@link Elmo.ForbiddenError}
     * @throws {@link Elmo.ConflictError}
     * @throws {@link Elmo.TooManyRequestsError}
     * @throws {@link Elmo.InternalServerError}
     * @throws {@link errors.ElmoError}
     * @throws {@link errors.ElmoTimeoutError}
     *
     * @example
     *     await client.reports.createReport({
     *         brandName: "brandName",
     *         brandWebsite: "brandWebsite"
     *     })
     */
    public createReport(
        request: Elmo.CreateReportRequest,
        requestOptions?: ReportsClient.RequestOptions,
    ): core.HttpResponsePromise<Elmo.CreateReportResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createReport(request, requestOptions));
    }

    private async __createReport(
        request: Elmo.CreateReportRequest,
        requestOptions?: ReportsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Elmo.CreateReportResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ElmoEnvironment.Default,
                "reports",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Elmo.CreateReportResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Elmo.BadRequestError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 401:
                    throw new Elmo.UnauthorizedError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 402:
                    throw new Elmo.PaymentRequiredError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 403:
                    throw new Elmo.ForbiddenError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 409:
                    throw new Elmo.ConflictError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 429:
                    throw new Elmo.TooManyRequestsError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 500:
                    throw new Elmo.InternalServerError(_response.error.body as Elmo.Error_, _response.rawResponse);
                default:
                    throw new errors.ElmoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/reports");
    }

    /**
     * Poll a report's status. When completed, returns per-prompt snapshot data with raw mention counts. Consumers are responsible for computing SoV and other derived metrics from the raw data.
     *
     * Requires an instance admin key; organization keys receive `403`.
     *
     * @param {Elmo.GetReportRequest} request
     * @param {ReportsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Elmo.BadRequestError}
     * @throws {@link Elmo.UnauthorizedError}
     * @throws {@link Elmo.ForbiddenError}
     * @throws {@link Elmo.NotFoundError}
     * @throws {@link Elmo.TooManyRequestsError}
     * @throws {@link Elmo.InternalServerError}
     * @throws {@link errors.ElmoError}
     * @throws {@link errors.ElmoTimeoutError}
     *
     * @example
     *     await client.reports.getReport({
     *         reportId: "reportId"
     *     })
     */
    public getReport(
        request: Elmo.GetReportRequest,
        requestOptions?: ReportsClient.RequestOptions,
    ): core.HttpResponsePromise<Elmo.GetReportResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getReport(request, requestOptions));
    }

    private async __getReport(
        request: Elmo.GetReportRequest,
        requestOptions?: ReportsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Elmo.GetReportResponse>> {
        const { reportId, kMentions } = request;
        const _queryParams: Record<string, unknown> = {
            kMentions,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ElmoEnvironment.Default,
                `reports/${core.url.encodePathParam(reportId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Elmo.GetReportResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Elmo.BadRequestError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 401:
                    throw new Elmo.UnauthorizedError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 403:
                    throw new Elmo.ForbiddenError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 404:
                    throw new Elmo.NotFoundError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 429:
                    throw new Elmo.TooManyRequestsError(_response.error.body as Elmo.Error_, _response.rawResponse);
                case 500:
                    throw new Elmo.InternalServerError(_response.error.body as Elmo.Error_, _response.rawResponse);
                default:
                    throw new errors.ElmoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/reports/{reportId}");
    }
}
