# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.prompt_snapshot import PromptSnapshot
from .raw_client import AsyncRawSnapshotsClient, RawSnapshotsClient


class SnapshotsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSnapshotsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSnapshotsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSnapshotsClient
        """
        return self._raw_client

    def get_prompt_snapshot(
        self,
        prompt_id: str,
        *,
        start_date: dt.date,
        end_date: dt.date,
        k_mentions: typing.Optional[int] = None,
        k_citations: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PromptSnapshot:
        """
        Get an aggregated snapshot of mention and citation analytics for a specific prompt over a date range. Use this to identify competitive gaps, track brand visibility trends, and discover top cited URLs.

        Parameters
        ----------
        prompt_id : str
            The ID of the prompt

        start_date : dt.date
            Start of date range (YYYY-MM-DD)

        end_date : dt.date
            End of date range (YYYY-MM-DD)

        k_mentions : typing.Optional[int]
            Number of top competitor entities to return in mentionsTopK

        k_citations : typing.Optional[int]
            Number of top cited URLs to return in citedUrlsTopK

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PromptSnapshot
            Prompt snapshot with mention and citation analytics

        Examples
        --------
        import datetime

        from elmohq_sdk import Elmo

        client = Elmo(
            token="YOUR_TOKEN",
        )
        client.snapshots.get_prompt_snapshot(
            prompt_id="promptId",
            start_date=datetime.date.fromisoformat(
                "2026-01-08",
            ),
            end_date=datetime.date.fromisoformat(
                "2026-01-15",
            ),
        )
        """
        _response = self._raw_client.get_prompt_snapshot(
            prompt_id,
            start_date=start_date,
            end_date=end_date,
            k_mentions=k_mentions,
            k_citations=k_citations,
            request_options=request_options,
        )
        return _response.data


class AsyncSnapshotsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSnapshotsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSnapshotsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSnapshotsClient
        """
        return self._raw_client

    async def get_prompt_snapshot(
        self,
        prompt_id: str,
        *,
        start_date: dt.date,
        end_date: dt.date,
        k_mentions: typing.Optional[int] = None,
        k_citations: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PromptSnapshot:
        """
        Get an aggregated snapshot of mention and citation analytics for a specific prompt over a date range. Use this to identify competitive gaps, track brand visibility trends, and discover top cited URLs.

        Parameters
        ----------
        prompt_id : str
            The ID of the prompt

        start_date : dt.date
            Start of date range (YYYY-MM-DD)

        end_date : dt.date
            End of date range (YYYY-MM-DD)

        k_mentions : typing.Optional[int]
            Number of top competitor entities to return in mentionsTopK

        k_citations : typing.Optional[int]
            Number of top cited URLs to return in citedUrlsTopK

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PromptSnapshot
            Prompt snapshot with mention and citation analytics

        Examples
        --------
        import asyncio
        import datetime

        from elmohq_sdk import AsyncElmo

        client = AsyncElmo(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.snapshots.get_prompt_snapshot(
                prompt_id="promptId",
                start_date=datetime.date.fromisoformat(
                    "2026-01-08",
                ),
                end_date=datetime.date.fromisoformat(
                    "2026-01-15",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_prompt_snapshot(
            prompt_id,
            start_date=start_date,
            end_date=end_date,
            k_mentions=k_mentions,
            k_citations=k_citations,
            request_options=request_options,
        )
        return _response.data
