// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id",
 *         name: "name",
 *         domains: ["domains"]
 *     }
 */
export interface CreateBrandRequest {
    id: string;
    name: string;
    /** Brand domains. The first entry is the primary website; remaining entries are additional domains. */
    domains: string[];
    aliases?: string[];
    competitors?: CreateBrandRequest.Competitors.Item[];
    prompts?: CreateBrandRequest.Prompts.Item[];
    /**
     * Organization to create the brand in.
     *
     * | | Omitted | Present |
     * | --- | --- | --- |
     * | **Organization key** | creates in the key's own organization | must name the key's own organization; any other value is a `400` |
     * | **Admin key** | provisions a new organization named after the brand id | creates in the named organization, which must already exist — `404` if it does not |
     *
     * An admin key omitting this field is currently the only way to create an organization over the API.
     */
    organizationId?: string;
}

export namespace CreateBrandRequest {
    export type Competitors = Competitors.Item[];

    export namespace Competitors {
        export interface Item {
            name: string;
            domains?: string[] | undefined;
            aliases?: string[] | undefined;
        }
    }

    export type Prompts = Prompts.Item[];

    export namespace Prompts {
        export interface Item {
            value: string;
            tags?: string[] | undefined;
            enabled?: boolean | undefined;
        }
    }
}
