// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         brandId: "brandId"
 *     }
 */
export interface GetBrandRequest {
    /** Brand identifier */
    brandId: string;
}
