// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         promptId: "promptId",
 *         startDate: "2026-01-08",
 *         endDate: "2026-01-15"
 *     }
 */
export interface GetPromptSnapshotRequest {
    /** The ID of the prompt */
    promptId: string;
    /** Start of date range (YYYY-MM-DD) */
    startDate: string;
    /** End of date range (YYYY-MM-DD) */
    endDate: string;
    /** Number of top competitor entities to return in mentionsTopK */
    kMentions?: number;
    /** Number of top cited URLs to return in citedUrlsTopK */
    kCitations?: number;
}
