// This file was auto-generated by Fern from our API Definition.

import type * as Elmo from "../../../index.js";

export interface DeletePromptResponse extends Elmo.Prompt {
    /** Number of related prompt_runs rows deleted by the cascade. */
    deletedRunsCount: number;
}
