# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .api_key_identity import ApiKeyIdentity
    from .api_key_identity_key_type import ApiKeyIdentityKeyType
    from .api_key_identity_rate_limit import ApiKeyIdentityRateLimit
    from .api_key_identity_rate_limit_window import ApiKeyIdentityRateLimitWindow
    from .api_key_identity_scopes_item import ApiKeyIdentityScopesItem
    from .billing_plan import BillingPlan
    from .billing_plan_interval import BillingPlanInterval
    from .billing_plan_standing import BillingPlanStanding
    from .brand import Brand
    from .brand_analytics import BrandAnalytics
    from .brand_analytics_share_of_voice import BrandAnalyticsShareOfVoice
    from .brand_analytics_totals import BrandAnalyticsTotals
    from .brand_analytics_visibility import BrandAnalyticsVisibility
    from .brand_opportunities import BrandOpportunities
    from .brand_opportunities_status import BrandOpportunitiesStatus
    from .brand_query_fanout import BrandQueryFanout
    from .brands_list import BrandsList
    from .citation_domain import CitationDomain
    from .citation_domain_category import CitationDomainCategory
    from .citation_domain_list import CitationDomainList
    from .citation_domain_list_totals import CitationDomainListTotals
    from .citation_url import CitationUrl
    from .citation_url_category import CitationUrlCategory
    from .citation_url_list import CitationUrlList
    from .citation_url_list_totals import CitationUrlListTotals
    from .citation_url_page_type import CitationUrlPageType
    from .cited_page import CitedPage
    from .cited_url_entry import CitedUrlEntry
    from .competitor import Competitor
    from .competitors_list import CompetitorsList
    from .date_range import DateRange
    from .error import Error
    from .fanout_query import FanoutQuery
    from .mention_entry import MentionEntry
    from .mentions_summary import MentionsSummary
    from .model import Model
    from .model_list import ModelList
    from .model_visibility import ModelVisibility
    from .onboarding_suggestion import OnboardingSuggestion
    from .onboarding_suggestion_competitors_item import OnboardingSuggestionCompetitorsItem
    from .onboarding_suggestion_suggested_prompts_item import OnboardingSuggestionSuggestedPromptsItem
    from .opportunity import Opportunity
    from .opportunity_category import OpportunityCategory
    from .opportunity_prompt import OpportunityPrompt
    from .organization import Organization
    from .organization_billing import OrganizationBilling
    from .organization_billing_usage import OrganizationBillingUsage
    from .organization_list import OrganizationList
    from .pagination import Pagination
    from .plan_limits import PlanLimits
    from .prompt import Prompt
    from .prompt_performance import PromptPerformance
    from .prompt_performance_list import PromptPerformanceList
    from .prompt_snapshot import PromptSnapshot
    from .prompt_snapshot_citations import PromptSnapshotCitations
    from .report_prompt_snapshot import ReportPromptSnapshot
    from .report_summary import ReportSummary
    from .report_summary_status import ReportSummaryStatus
    from .run import Run
    from .run_answer import RunAnswer
    from .run_citation import RunCitation
    from .run_list import RunList
    from .run_summary import RunSummary
    from .share_of_voice_entry import ShareOfVoiceEntry
    from .share_of_voice_point import ShareOfVoicePoint
    from .tag import Tag
    from .tag_list import TagList
    from .visibility_point import VisibilityPoint
_dynamic_imports: typing.Dict[str, str] = {
    "ApiKeyIdentity": ".api_key_identity",
    "ApiKeyIdentityKeyType": ".api_key_identity_key_type",
    "ApiKeyIdentityRateLimit": ".api_key_identity_rate_limit",
    "ApiKeyIdentityRateLimitWindow": ".api_key_identity_rate_limit_window",
    "ApiKeyIdentityScopesItem": ".api_key_identity_scopes_item",
    "BillingPlan": ".billing_plan",
    "BillingPlanInterval": ".billing_plan_interval",
    "BillingPlanStanding": ".billing_plan_standing",
    "Brand": ".brand",
    "BrandAnalytics": ".brand_analytics",
    "BrandAnalyticsShareOfVoice": ".brand_analytics_share_of_voice",
    "BrandAnalyticsTotals": ".brand_analytics_totals",
    "BrandAnalyticsVisibility": ".brand_analytics_visibility",
    "BrandOpportunities": ".brand_opportunities",
    "BrandOpportunitiesStatus": ".brand_opportunities_status",
    "BrandQueryFanout": ".brand_query_fanout",
    "BrandsList": ".brands_list",
    "CitationDomain": ".citation_domain",
    "CitationDomainCategory": ".citation_domain_category",
    "CitationDomainList": ".citation_domain_list",
    "CitationDomainListTotals": ".citation_domain_list_totals",
    "CitationUrl": ".citation_url",
    "CitationUrlCategory": ".citation_url_category",
    "CitationUrlList": ".citation_url_list",
    "CitationUrlListTotals": ".citation_url_list_totals",
    "CitationUrlPageType": ".citation_url_page_type",
    "CitedPage": ".cited_page",
    "CitedUrlEntry": ".cited_url_entry",
    "Competitor": ".competitor",
    "CompetitorsList": ".competitors_list",
    "DateRange": ".date_range",
    "Error": ".error",
    "FanoutQuery": ".fanout_query",
    "MentionEntry": ".mention_entry",
    "MentionsSummary": ".mentions_summary",
    "Model": ".model",
    "ModelList": ".model_list",
    "ModelVisibility": ".model_visibility",
    "OnboardingSuggestion": ".onboarding_suggestion",
    "OnboardingSuggestionCompetitorsItem": ".onboarding_suggestion_competitors_item",
    "OnboardingSuggestionSuggestedPromptsItem": ".onboarding_suggestion_suggested_prompts_item",
    "Opportunity": ".opportunity",
    "OpportunityCategory": ".opportunity_category",
    "OpportunityPrompt": ".opportunity_prompt",
    "Organization": ".organization",
    "OrganizationBilling": ".organization_billing",
    "OrganizationBillingUsage": ".organization_billing_usage",
    "OrganizationList": ".organization_list",
    "Pagination": ".pagination",
    "PlanLimits": ".plan_limits",
    "Prompt": ".prompt",
    "PromptPerformance": ".prompt_performance",
    "PromptPerformanceList": ".prompt_performance_list",
    "PromptSnapshot": ".prompt_snapshot",
    "PromptSnapshotCitations": ".prompt_snapshot_citations",
    "ReportPromptSnapshot": ".report_prompt_snapshot",
    "ReportSummary": ".report_summary",
    "ReportSummaryStatus": ".report_summary_status",
    "Run": ".run",
    "RunAnswer": ".run_answer",
    "RunCitation": ".run_citation",
    "RunList": ".run_list",
    "RunSummary": ".run_summary",
    "ShareOfVoiceEntry": ".share_of_voice_entry",
    "ShareOfVoicePoint": ".share_of_voice_point",
    "Tag": ".tag",
    "TagList": ".tag_list",
    "VisibilityPoint": ".visibility_point",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ApiKeyIdentity",
    "ApiKeyIdentityKeyType",
    "ApiKeyIdentityRateLimit",
    "ApiKeyIdentityRateLimitWindow",
    "ApiKeyIdentityScopesItem",
    "BillingPlan",
    "BillingPlanInterval",
    "BillingPlanStanding",
    "Brand",
    "BrandAnalytics",
    "BrandAnalyticsShareOfVoice",
    "BrandAnalyticsTotals",
    "BrandAnalyticsVisibility",
    "BrandOpportunities",
    "BrandOpportunitiesStatus",
    "BrandQueryFanout",
    "BrandsList",
    "CitationDomain",
    "CitationDomainCategory",
    "CitationDomainList",
    "CitationDomainListTotals",
    "CitationUrl",
    "CitationUrlCategory",
    "CitationUrlList",
    "CitationUrlListTotals",
    "CitationUrlPageType",
    "CitedPage",
    "CitedUrlEntry",
    "Competitor",
    "CompetitorsList",
    "DateRange",
    "Error",
    "FanoutQuery",
    "MentionEntry",
    "MentionsSummary",
    "Model",
    "ModelList",
    "ModelVisibility",
    "OnboardingSuggestion",
    "OnboardingSuggestionCompetitorsItem",
    "OnboardingSuggestionSuggestedPromptsItem",
    "Opportunity",
    "OpportunityCategory",
    "OpportunityPrompt",
    "Organization",
    "OrganizationBilling",
    "OrganizationBillingUsage",
    "OrganizationList",
    "Pagination",
    "PlanLimits",
    "Prompt",
    "PromptPerformance",
    "PromptPerformanceList",
    "PromptSnapshot",
    "PromptSnapshotCitations",
    "ReportPromptSnapshot",
    "ReportSummary",
    "ReportSummaryStatus",
    "Run",
    "RunAnswer",
    "RunCitation",
    "RunList",
    "RunSummary",
    "ShareOfVoiceEntry",
    "ShareOfVoicePoint",
    "Tag",
    "TagList",
    "VisibilityPoint",
]
