# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .api_key_identity_key_type import ApiKeyIdentityKeyType
from .api_key_identity_rate_limit import ApiKeyIdentityRateLimit
from .api_key_identity_scopes_item import ApiKeyIdentityScopesItem


class ApiKeyIdentity(UniversalBaseModel):
    key_type: typing_extensions.Annotated[
        ApiKeyIdentityKeyType,
        FieldMetadata(alias="keyType"),
        pydantic.Field(
            alias="keyType", description="`admin` for an instance key, `organization` for a dashboard-issued key."
        ),
    ]
    """
    `admin` for an instance key, `organization` for a dashboard-issued key.
    """

    organization_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="organizationId"),
        pydantic.Field(
            alias="organizationId", description="The organization this key acts inside. Null for admin keys."
        ),
    ] = None
    """
    The organization this key acts inside. Null for admin keys.
    """

    organization_name: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="organizationName"), pydantic.Field(alias="organizationName")
    ] = None
    scopes: typing.List[ApiKeyIdentityScopesItem] = pydantic.Field()
    """
    Scopes this key holds. A read-write key lists both; an admin key always does.
    """

    brand_ids: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="brandIds"),
        pydantic.Field(
            alias="brandIds",
            description="Brands the key is narrowed to, or null when it reaches every brand in its organization. Never an empty array — a restriction to no brands is rejected at creation rather than treated as no restriction.",
        ),
    ] = None
    """
    Brands the key is narrowed to, or null when it reaches every brand in its organization. Never an empty array — a restriction to no brands is rejected at creation rather than treated as no restriction.
    """

    created_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ] = None
    expires_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="expiresAt"),
        pydantic.Field(alias="expiresAt", description="When the key stops working, if it has an expiry."),
    ] = None
    """
    When the key stops working, if it has an expiry.
    """

    rate_limit: typing_extensions.Annotated[
        typing.Optional[ApiKeyIdentityRateLimit],
        FieldMetadata(alias="rateLimit"),
        pydantic.Field(
            alias="rateLimit",
            description="The key's configured limit — generous by design: it exists to stop a runaway loop, not to meter normal use. Enforcement is a fixed window and approximate under concurrency.",
        ),
    ] = None
    """
    The key's configured limit — generous by design: it exists to stop a runaway loop, not to meter normal use. Enforcement is a fixed window and approximate under concurrency.
    """

    created_by: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="createdBy"),
        pydantic.Field(
            alias="createdBy", description="The key's label, as given when it was issued. Null for admin keys."
        ),
    ] = None
    """
    The key's label, as given when it was issued. Null for admin keys.
    """

    last_used_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="lastUsedAt"), pydantic.Field(alias="lastUsedAt")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
