# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .billing_plan_interval import BillingPlanInterval
from .billing_plan_standing import BillingPlanStanding


class BillingPlan(UniversalBaseModel):
    key: typing.Optional[str] = pydantic.Field(default=None)
    """
    Plan identifier, or `custom` for a negotiated plan.
    """

    name: str = pydantic.Field()
    """
    Display name.
    """

    standing: BillingPlanStanding = pydantic.Field()
    """
    What the subscription means for service, and the only field a caller needs to act on: `active` and `grace` keep tracking running, `paused` stops it, `none` is unsubscribed. The payment provider's own status string is deliberately not passed through.
    """

    interval: typing.Optional[BillingPlanInterval] = pydantic.Field(default=None)
    """
    Null on a negotiated plan, which carries no billing interval.
    """

    period_end: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="periodEnd"), pydantic.Field(alias="periodEnd")
    ] = None
    cancel_at_period_end: typing_extensions.Annotated[
        bool, FieldMetadata(alias="cancelAtPeriodEnd"), pydantic.Field(alias="cancelAtPeriodEnd")
    ]
    tracking_active: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="trackingActive"),
        pydantic.Field(alias="trackingActive", description="Whether prompts are currently being sampled."),
    ]
    """
    Whether prompts are currently being sampled.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
