# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .date_range import DateRange
from .fanout_query import FanoutQuery


class BrandQueryFanout(UniversalBaseModel):
    brand_id: typing_extensions.Annotated[str, FieldMetadata(alias="brandId"), pydantic.Field(alias="brandId")]
    range: DateRange
    total_queries: typing_extensions.Annotated[
        int, FieldMetadata(alias="totalQueries"), pydantic.Field(alias="totalQueries")
    ]
    unique_queries: typing_extensions.Annotated[
        int, FieldMetadata(alias="uniqueQueries"), pydantic.Field(alias="uniqueQueries")
    ]
    fanout_runs: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="fanoutRuns"),
        pydantic.Field(
            alias="fanoutRuns",
            description="Runs that searched at all. Engines that don't expose their searches contribute runs but no queries.",
        ),
    ]
    """
    Runs that searched at all. Engines that don't expose their searches contribute runs but no queries.
    """

    total_runs: typing_extensions.Annotated[int, FieldMetadata(alias="totalRuns"), pydantic.Field(alias="totalRuns")]
    avg_queries_per_run: typing_extensions.Annotated[
        float, FieldMetadata(alias="avgQueriesPerRun"), pydantic.Field(alias="avgQueriesPerRun")
    ]
    coverage_rate: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="coverageRate"),
        pydantic.Field(
            alias="coverageRate",
            description="Share of fan-out query instances whose answer mentioned the brand. Ratio 0–1; multiply by 100 for a percentage.",
        ),
    ]
    """
    Share of fan-out query instances whose answer mentioned the brand. Ratio 0–1; multiply by 100 for a percentage.
    """

    data: typing.List[FanoutQuery] = pydantic.Field()
    """
    Every distinct sub-query over the window, ordered by the runs that ran it.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
