# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .share_of_voice_entry import ShareOfVoiceEntry
from .share_of_voice_point import ShareOfVoicePoint


class BrandAnalyticsShareOfVoice(UniversalBaseModel):
    """
    The brand against its tracked competitors.
    """

    brand: typing.Optional[float] = pydantic.Field(default=None)
    """
    The brand's own share at the end of the window. Ratio 0–1; multiply by 100 for a percentage.
    """

    entries: typing.List[ShareOfVoiceEntry] = pydantic.Field()
    """
    Leaderboard, highest share first.
    """

    series: typing.List[ShareOfVoicePoint] = pydantic.Field()
    """
    The brand's share over time.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
