# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .brand_opportunities_status import BrandOpportunitiesStatus
from .opportunity import Opportunity


class BrandOpportunities(UniversalBaseModel):
    """
    The brand's latest Opportunities report — the same LLM-generated analysis the dashboard shows, read from the append-only history rather than regenerated. Elmo decides when to produce a new one; there is no way to trigger generation over the API, because it spends provider budget with no per-call metering behind it.
    """

    brand_id: typing_extensions.Annotated[str, FieldMetadata(alias="brandId"), pydantic.Field(alias="brandId")]
    status: BrandOpportunitiesStatus = pydantic.Field()
    """
    `ready` when a report is present. `insufficient-data` when the brand hasn't accumulated enough tracked answers to say anything useful yet, in which case the lists are empty.
    """

    generated_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="generatedAt"), pydantic.Field(alias="generatedAt")
    ] = None
    model: typing.Optional[str] = pydantic.Field(default=None)
    """
    The model that produced the report, when recorded.
    """

    summary: typing.List[str] = pydantic.Field()
    """
    A few bullets on where the brand stands and the through-line of the plan.
    """

    opportunities: typing.List[Opportunity] = pydantic.Field()
    """
    Prioritized, highest impact first.
    """

    risks: typing.List[str] = pydantic.Field()
    """
    Caveats: hard-to-win areas, or tactics to avoid.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
