# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .citation_domain_category import CitationDomainCategory


class CitationDomain(UniversalBaseModel):
    domain: str
    category: CitationDomainCategory = pydantic.Field()
    """
    Which side of the citation landscape the domain sits on.
    """

    count: int = pydantic.Field()
    """
    Citations to this domain in the window.
    """

    share: float = pydantic.Field()
    """
    Share of all citations in the window. Ratio 0–1; multiply by 100 for a percentage.
    """

    prompt_count: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="promptCount"),
        pydantic.Field(alias="promptCount", description="Distinct prompts whose answers cited this domain."),
    ]
    """
    Distinct prompts whose answers cited this domain.
    """

    previous_count: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="previousCount"),
        pydantic.Field(
            alias="previousCount", description="Citations in the equal-length window immediately before this one."
        ),
    ]
    """
    Citations in the equal-length window immediately before this one.
    """

    change_factor: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="changeFactor"),
        pydantic.Field(
            alias="changeFactor",
            description='How this window compares with the equal-length window before it, as a multiplier of the previous count: 2 means twice as many citations, 0.5 means half, 1 means unchanged. Not a percentage change — 1.5 is "1.5x", which is a 50% increase. Null when the domain had no citations in the previous window, so there is nothing to divide by.',
        ),
    ] = None
    """
    How this window compares with the equal-length window before it, as a multiplier of the previous count: 2 means twice as many citations, 0.5 means half, 1 means unchanged. Not a percentage change — 1.5 is "1.5x", which is a 50% increase. Null when the domain had no citations in the previous window, so there is nothing to divide by.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
