# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .citation_url import CitationUrl
from .citation_url_list_totals import CitationUrlListTotals
from .date_range import DateRange


class CitationUrlList(UniversalBaseModel):
    brand_id: typing_extensions.Annotated[str, FieldMetadata(alias="brandId"), pydantic.Field(alias="brandId")]
    range: DateRange
    totals: CitationUrlListTotals
    data: typing.List[CitationUrl] = pydantic.Field()
    """
    Every URL cited over the window, ordered by citation count.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
