# This file was auto-generated by Fern from our API Definition.

import typing

CitationUrlCategory = typing.Union[
    typing.Literal[
        "brand",
        "competitor",
        "editorial",
        "reviews",
        "ecommerce",
        "social",
        "developer",
        "pr",
        "reference",
        "institutional",
        "other",
    ],
    typing.Any,
]
