# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .citation_domain import CitationDomain
from .citation_domain_list_totals import CitationDomainListTotals
from .date_range import DateRange


class CitationDomainList(UniversalBaseModel):
    brand_id: typing_extensions.Annotated[str, FieldMetadata(alias="brandId"), pydantic.Field(alias="brandId")]
    range: DateRange
    totals: CitationDomainListTotals
    data: typing.List[CitationDomain] = pydantic.Field()
    """
    Every domain cited over the window, ordered by citation count.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
