# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .citation_url_category import CitationUrlCategory
from .citation_url_page_type import CitationUrlPageType


class CitationUrl(UniversalBaseModel):
    url: str
    domain: str
    title: typing.Optional[str] = None
    category: CitationUrlCategory = pydantic.Field()
    """
    Which side of the citation landscape the domain sits on.
    """

    page_type: typing_extensions.Annotated[
        CitationUrlPageType,
        FieldMetadata(alias="pageType"),
        pydantic.Field(alias="pageType", description="What kind of page was cited."),
    ]
    """
    What kind of page was cited.
    """

    count: int
    prompt_count: typing_extensions.Annotated[
        int, FieldMetadata(alias="promptCount"), pydantic.Field(alias="promptCount")
    ]
    is_new: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="isNew"),
        pydantic.Field(alias="isNew", description="Not cited in the equal-length window immediately before this one."),
    ]
    """
    Not cited in the equal-length window immediately before this one.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
