# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class FanoutQuery(UniversalBaseModel):
    query: str = pydantic.Field()
    """
    A search the engine ran while answering.
    """

    runs: int
    prompt_count: typing_extensions.Annotated[
        int, FieldMetadata(alias="promptCount"), pydantic.Field(alias="promptCount")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
