# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .mention_entry import MentionEntry


class MentionsSummary(UniversalBaseModel):
    """
    Aggregated mention counts for a prompt across its evaluation runs.
    """

    mentions_total: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="mentionsTotal"),
        pydantic.Field(alias="mentionsTotal", description="Total brand + competitor mentions across all runs"),
    ]
    """
    Total brand + competitor mentions across all runs
    """

    brand_mentions_total: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="brandMentionsTotal"),
        pydantic.Field(alias="brandMentionsTotal", description="Number of runs where the brand was mentioned"),
    ]
    """
    Number of runs where the brand was mentioned
    """

    competitor_mentions_total: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="competitorMentionsTotal"),
        pydantic.Field(
            alias="competitorMentionsTotal",
            description="Total count of individual competitor mentions across all runs (a single run mentioning 3 competitors counts as 3)",
        ),
    ]
    """
    Total count of individual competitor mentions across all runs (a single run mentioning 3 competitors counts as 3)
    """

    mentions_top_k: typing_extensions.Annotated[
        typing.List[MentionEntry],
        FieldMetadata(alias="mentionsTopK"),
        pydantic.Field(alias="mentionsTopK", description="Top-K competitor entities ranked by mention count"),
    ]
    """
    Top-K competitor entities ranked by mention count
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
