# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class Model(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Identifier used by the `model` filter, e.g. `chatgpt`.
    """

    label: str = pydantic.Field()
    """
    Human-readable name.
    """

    premium_capable: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="premiumCapable"),
        pydantic.Field(
            alias="premiumCapable",
            description="Whether this model can be tracked grounded, spending a premium pairing.",
        ),
    ]
    """
    Whether this model can be tracked grounded, spending a premium pairing.
    """

    configured: bool = pydantic.Field()
    """
    Whether this deployment is actually wired to reach it.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
