# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .onboarding_suggestion_competitors_item import OnboardingSuggestionCompetitorsItem
from .onboarding_suggestion_suggested_prompts_item import OnboardingSuggestionSuggestedPromptsItem


class OnboardingSuggestion(UniversalBaseModel):
    brand_name: typing_extensions.Annotated[str, FieldMetadata(alias="brandName"), pydantic.Field(alias="brandName")]
    website: str = pydantic.Field()
    """
    Cleaned hostname
    """

    additional_domains: typing_extensions.Annotated[
        typing.List[str], FieldMetadata(alias="additionalDomains"), pydantic.Field(alias="additionalDomains")
    ]
    aliases: typing.List[str]
    competitors: typing.List[OnboardingSuggestionCompetitorsItem]
    suggested_prompts: typing_extensions.Annotated[
        typing.List[OnboardingSuggestionSuggestedPromptsItem],
        FieldMetadata(alias="suggestedPrompts"),
        pydantic.Field(alias="suggestedPrompts"),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
