# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class OpportunityPrompt(UniversalBaseModel):
    text: str = pydantic.Field()
    """
    The prompt as the report names it.
    """

    prompt_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="promptId"),
        pydantic.Field(
            alias="promptId", description="The tracked prompt it resolved to, or null when it didn't match one."
        ),
    ] = None
    """
    The tracked prompt it resolved to, or null when it didn't match one.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
