# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .cited_page import CitedPage
from .opportunity_category import OpportunityCategory
from .opportunity_prompt import OpportunityPrompt


class Opportunity(UniversalBaseModel):
    category: OpportunityCategory = pydantic.Field()
    """
    Which workstream this belongs to: `creation` is net-new content, `existing-content` is a page that could win the mention with a refresh, `outreach` is earning a placement on a third-party site assistants cite, `social` is the community conversations they pull from.
    """

    title: str = pydantic.Field()
    """
    Short and action-oriented — the concrete surface or angle.
    """

    why: str = pydantic.Field()
    """
    Why it is worth doing, in plain language.
    """

    related_prompts: typing_extensions.Annotated[
        typing.List[OpportunityPrompt],
        FieldMetadata(alias="relatedPrompts"),
        pydantic.Field(alias="relatedPrompts", description="Tracked prompts this would help. May be empty."),
    ]
    """
    Tracked prompts this would help. May be empty.
    """

    your_citations: typing_extensions.Annotated[
        typing.List[CitedPage],
        FieldMetadata(alias="yourCitations"),
        pydantic.Field(
            alias="yourCitations", description="Pages on the brand's own domains already cited for those prompts."
        ),
    ]
    """
    Pages on the brand's own domains already cited for those prompts.
    """

    competitor_citations: typing_extensions.Annotated[
        typing.List[CitedPage],
        FieldMetadata(alias="competitorCitations"),
        pydantic.Field(alias="competitorCitations", description="Pages on competitor domains cited for those prompts."),
    ]
    """
    Pages on competitor domains cited for those prompts.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
