# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .billing_plan import BillingPlan
from .organization_billing_usage import OrganizationBillingUsage
from .plan_limits import PlanLimits


class OrganizationBilling(UniversalBaseModel):
    """
    Read-only view of an organization's subscription, limits, and usage. The API has no way to change any of it: there is no billing write endpoint and no billing write scope. Stripe identifiers, payment methods, and invoices are deliberately not exposed — those live in the Stripe customer portal.
    """

    organization_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="organizationId"), pydantic.Field(alias="organizationId")
    ]
    billing_enabled: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="billingEnabled"),
        pydantic.Field(
            alias="billingEnabled", description="False on self-hosted deployments, where nothing is metered."
        ),
    ]
    """
    False on self-hosted deployments, where nothing is metered.
    """

    plan: typing.Optional[BillingPlan] = pydantic.Field(default=None)
    """
    Null when the organization has no subscription, or when billing is disabled.
    """

    limits: typing.Optional[PlanLimits] = None
    usage: OrganizationBillingUsage

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
