# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class PromptPerformance(UniversalBaseModel):
    prompt_id: typing_extensions.Annotated[str, FieldMetadata(alias="promptId"), pydantic.Field(alias="promptId")]
    value: str
    tags: typing.List[str]
    total_runs: typing_extensions.Annotated[int, FieldMetadata(alias="totalRuns"), pydantic.Field(alias="totalRuns")]
    brand_mention_rate: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="brandMentionRate"),
        pydantic.Field(
            alias="brandMentionRate",
            description="Share of this prompt's runs mentioning the brand. Ratio 0–1; multiply by 100 for a percentage.",
        ),
    ]
    """
    Share of this prompt's runs mentioning the brand. Ratio 0–1; multiply by 100 for a percentage.
    """

    competitor_mention_rate: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="competitorMentionRate"),
        pydantic.Field(
            alias="competitorMentionRate",
            description="Share of this prompt's runs mentioning any tracked competitor. Ratio 0–1; multiply by 100 for a percentage.",
        ),
    ]
    """
    Share of this prompt's runs mentioning any tracked competitor. Ratio 0–1; multiply by 100 for a percentage.
    """

    last_run_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="lastRunAt"), pydantic.Field(alias="lastRunAt")
    ] = None
    first_evaluated_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="firstEvaluatedAt"), pydantic.Field(alias="firstEvaluatedAt")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
