# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class Prompt(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Unique identifier for the prompt
    """

    brand_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="brandId"),
        pydantic.Field(alias="brandId", description="Brand identifier this prompt belongs to"),
    ]
    """
    Brand identifier this prompt belongs to
    """

    value: str = pydantic.Field()
    """
    The actual prompt text
    """

    enabled: bool = pydantic.Field()
    """
    Whether the prompt is currently enabled
    """

    tags: typing.List[str] = pydantic.Field()
    """
    User-defined tags for categorizing this prompt
    """

    system_tags: typing_extensions.Annotated[
        typing.List[str],
        FieldMetadata(alias="systemTags"),
        pydantic.Field(
            alias="systemTags", description="Auto-computed system tags (e.g., 'branded', 'unbranded'). Read-only."
        ),
    ]
    """
    Auto-computed system tags (e.g., 'branded', 'unbranded'). Read-only.
    """

    created_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="Timestamp when the prompt was created"),
    ]
    """
    Timestamp when the prompt was created
    """

    updated_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="updatedAt"),
        pydantic.Field(alias="updatedAt", description="Timestamp when the prompt was last updated"),
    ]
    """
    Timestamp when the prompt was last updated
    """

    premium_models: typing_extensions.Annotated[
        typing.List[str],
        FieldMetadata(alias="premiumModels"),
        pydantic.Field(
            alias="premiumModels",
            description="Models this prompt is tracked on grounded. Each entry spends one premium pairing.",
        ),
    ]
    """
    Models this prompt is tracked on grounded. Each entry spends one premium pairing.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
