# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .report_summary_status import ReportSummaryStatus


class ReportSummary(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Unique identifier for the report
    """

    brand_name: typing_extensions.Annotated[
        str, FieldMetadata(alias="brandName"), pydantic.Field(alias="brandName", description="Brand name analyzed")
    ]
    """
    Brand name analyzed
    """

    brand_aliases: typing_extensions.Annotated[
        typing.List[str],
        FieldMetadata(alias="brandAliases"),
        pydantic.Field(alias="brandAliases", description="Other names counted as brand mentions"),
    ]
    """
    Other names counted as brand mentions
    """

    brand_website: typing_extensions.Annotated[
        str, FieldMetadata(alias="brandWebsite"), pydantic.Field(alias="brandWebsite", description="Brand website URL")
    ]
    """
    Brand website URL
    """

    status: ReportSummaryStatus = pydantic.Field()
    """
    Current report status
    """

    created_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="Timestamp when the report was created"),
    ]
    """
    Timestamp when the report was created
    """

    completed_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="completedAt"),
        pydantic.Field(alias="completedAt", description="Timestamp when the report completed"),
    ] = None
    """
    Timestamp when the report completed
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
