# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class RunCitation(UniversalBaseModel):
    url: str
    domain: str
    title: typing.Optional[str] = None
    citation_index: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="citationIndex"),
        pydantic.Field(alias="citationIndex", description="Position within the answer's citation list."),
    ]
    """
    Position within the answer's citation list.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
