# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class Tag(UniversalBaseModel):
    name: str = pydantic.Field()
    """
    The tag, normalized to lower case.
    """

    prompt_count: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="promptCount"),
        pydantic.Field(alias="promptCount", description="Prompts in this brand carrying the tag."),
    ]
    """
    Prompts in this brand carrying the tag.
    """

    system: bool = pydantic.Field()
    """
    True for `branded` and `unbranded`, which Elmo computes from the prompt text. A system tag always appears here; applying it to a prompt as a user tag overrides the computed classification rather than creating a new tag.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
